// Sections with their IDs
export const INDOOR_SERVICE_SECTIONS = {
  ELECTRICAL: "Electrical",
  PLUMBING: "Plumbing",
  PAINTING: "Painting",
  TILING: "Tiling",
  FLOORING: "Flooring",
  CARPENTRY: "Carpentry",
  HVAC: "HVAC",
  CLEANING: "Cleaning",
  WALL_AND_CEILING: "Wall and Ceiling",
  APPLIANCE: "Appliance",
  SECURITY: "Security",
  AUDIO_VISUAL: "Audio-Visual",
  FURNITURE: "Furniture",
  MOVING: "Moving",
} as const;

export const OUTDOOR_SERVICE_SECTIONS = {
  OUTDOOR_PAINTING: "Outdoor Painting",
  OUTDOOR_CARPENTRY: "Outdoor Carpentry",
  OUTDOOR_ELECTRICAL: "Outdoor Electrical",
  OUTDOOR_CLEANING: "Outdoor Cleaning",
  OUTDOOR_LIGHTING: "Outdoor Lighting",
  ROOFING: "Roofing",
  LANDSCAPING: "Landscaping",
  OUTDOOR_APPLIANCE: "Outdoor Appliance",
  FACADE: "Facade",
  OUTDOOR_SECURITY: "Outdoor Security",
} as const;

export const ALL_CATEGORIES = [
  { id: "1-1", title: "Smoke Detector", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-2", title: "Ceiling fan", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-3", title: "Light fixture", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-4", title: "Switch", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-5", title: "Outlet", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-6", title: "Dimmer Switch", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-7", title: "Chandelier", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-8", title: "Wiring", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-9", title: "Troubleshooting", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "1-10", title: "Track Lighting", section: INDOOR_SERVICE_SECTIONS.ELECTRICAL },
  { id: "2-1", title: "Toilet", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-2", title: "Shower", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-3", title: "Bathtub", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-4", title: "Sink", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-5", title: "Faucet", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-6", title: "Water Heater", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-7", title: "Garbage Disposal", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-8", title: "Clogged Drain", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "2-9", title: "Pipes", section: INDOOR_SERVICE_SECTIONS.PLUMBING },
  { id: "3-1", title: "Walls", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-2", title: "Ceilings", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-3", title: "Acoustic Ceiling", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-4", title: "Trim and Molding", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-5", title: "Doors", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-6", title: "Windows", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-7", title: "Cabinetry", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-8", title: "Wallpaper", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-9", title: "Concrete and Masonry", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "3-10", title: "Baseboard", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "4-1", title: "Ceramic", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-2", title: "Porcelain", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-3", title: "Natural Stone", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-4", title: "Mosaic", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-5", title: "Bathroom", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-6", title: "Kitchen", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-7", title: "Fireplace", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-8", title: "Subfloor", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-9", title: "Vanity Top", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "4-10", title: "Underfloor Heating", section: INDOOR_SERVICE_SECTIONS.TILING },
  { id: "5-1", title: "Carpet", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-2", title: "Carpet Pad", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-3", title: "Vinyl Tile", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-4", title: "Vinyl Covering", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-5", title: "Laminate", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-6", title: "Bamboo Flooring", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-7", title: "Wood floor", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-8", title: "Solid wood", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-9", title: "Engineered Wood", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-10", title: "Underlayment", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "5-11", title: "Baseboard", section: INDOOR_SERVICE_SECTIONS.FLOORING },
  { id: "6-1", title: "Cabinet", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-2", title: "Trim and Molding", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-3", title: "Framing", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-4", title: "Beam and Column", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-5", title: "Foundation", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-6", title: "Doors", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-7", title: "Windows", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-8", title: "Stairs", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-9", title: "Wood Paneling", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "6-10", title: "Countertop", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "7-1", title: "Furnace", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-2", title: "Boiler", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-3", title: "Heat Pump", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-4", title: "Mini Split Air Conditioner", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-5", title: "Window AC", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-6", title: "Ventilation System", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-7", title: "Ductwork", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-8", title: "Thermostat", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-9", title: "Heater", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-10", title: "Air Quality", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-11", title: "Freestanding Stoves", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "7-12", title: "Fireplaces", section: INDOOR_SERVICE_SECTIONS.HVAC },
  { id: "12-1", title: "Regular Cleaning", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-2", title: "General Cleaning", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-3", title: "Specialized", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-4", title: "Windows", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-5", title: "Janitorial", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-6", title: "Post-Event", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-7", title: "Emergency", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "12-8", title: "Biohazard", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "13-1", title: "Drywall repair", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-2", title: "Texture drywall", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-3", title: "Acoustic Drywall", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-4", title: "Drywall Installation", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-5", title: "Venetian Plaster", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-6", title: "Ceiling Drywall", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-7", title: "Drywall Finishing", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-8", title: "Specialty Drywall", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-9", title: "Drywall Demolition", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "13-10", title: "Bricks", section: INDOOR_SERVICE_SECTIONS.WALL_AND_CEILING },
  { id: "14-1", title: "Refrigerator", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-2", title: "Oven", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-3", title: "Dishwasher", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-4", title: "Washer", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-5", title: "Dryer", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-6", title: "Microwave", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-7", title: "Range Hood", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "14-8", title: "Diagnostic", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "15-1", title: "Alarm System", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-2", title: "CCTV", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-3", title: "Smart Lock", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-4", title: "Intercom System", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-5", title: "Access Control", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-6", title: "Motion Sensor", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-7", title: "Door Sensor", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "15-8", title: "Water Detector", section: INDOOR_SERVICE_SECTIONS.SECURITY },
  { id: "16-1", title: "Projector", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-2", title: "Screen", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-3", title: "Sound System", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-4", title: "Speaker", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-5", title: "AV Receiver", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-6", title: "Cable and Wire", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-7", title: "TV Wall", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-8", title: "Wi-Fi", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-9", title: "Sound Absorbing", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "16-10", title: "Troubleshooting", section: INDOOR_SERVICE_SECTIONS.AUDIO_VISUAL },
  { id: "17-1", title: "Assembly", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-2", title: "Installation", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-3", title: "Repair", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-4", title: "Cleaning", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-5", title: "Storage", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-6", title: "Upholstery", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-7", title: "Removal", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "17-8", title: "Commercial", section: INDOOR_SERVICE_SECTIONS.FURNITURE },
  { id: "21-1", title: "Residential Local", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "21-2", title: "Commercial Local", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "21-3", title: "Packing/Unpacking", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "21-4", title: "Specialty", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "21-5", title: "Storage Solutions", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "21-6", title: "Cleaning Services", section: INDOOR_SERVICE_SECTIONS.MOVING },
  { id: "8-1", title: "Exterior Wall", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-2", title: "Fence", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-3", title: "Deck", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-4", title: "Window Trim", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-5", title: "Doors", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-6", title: "Shutter", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-7", title: "Trim", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-8", title: "Stucco", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-9", title: "Brick", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "8-10", title: "Concrete", section: INDOOR_SERVICE_SECTIONS.PAINTING },
  { id: "9-1", title: "Deck", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-2", title: "Fence", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-3", title: "Pergola", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-4", title: "Gazebo", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-5", title: "Outdoor Furniture", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-6", title: "Storage", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-7", title: "Playground", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-8", title: "Staircases", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-9", title: "Walkway", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-10", title: "Dock", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-11", title: "Floating dock", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "9-12", title: "Maintenance", section: INDOOR_SERVICE_SECTIONS.CARPENTRY },
  { id: "10-1", title: "Electrical Panel", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-2", title: "Outlet and Switch", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-3", title: "EV Chargers", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-4", title: "Pool and Spa", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-5", title: "Ceiling Fans", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-6", title: "AUDIO_VISUAL", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-7", title: "Backup Power", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-8", title: "Safety Inspections", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-9", title: "Solar Panels", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "10-10", title: "Maintenance", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_ELECTRICAL },
  { id: "11-1", title: "Deck and Patio", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-2", title: "Driveway", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-3", title: "Hot Tub", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-4", title: "House Washing", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-5", title: "Fence", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-6", title: "Gutter", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-7", title: "Roof", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-8", title: "Exterior Fixture", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-9", title: "Pool", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "11-10", title: "Doors and Window", section: INDOOR_SERVICE_SECTIONS.CLEANING },
  { id: "18-1", title: "Path Lights", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-2", title: "Deck and Patio", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-3", title: "Wall Lights", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-4", title: "Security Lighting", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-5", title: "Pool Lighting", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-6", title: "Smart Lighting", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-7", title: "Christmas Lights", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "18-8", title: "Maintenance", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_LIGHTING },
  { id: "19-1", title: "Leak Repair", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-2", title: "Shingle Roof", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-3", title: "Metal Roof", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-4", title: "Tile Roof", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-5", title: "Flat Roof", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-6", title: "Roof Inspection", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-7", title: "Gutter", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-8", title: "Roof Ventilation", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-9", title: "Skylight", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "19-10", title: "Sheathing", section: OUTDOOR_SERVICE_SECTIONS.ROOFING },
  { id: "20-1", title: "Lawn Maintenance", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-2", title: "Lawn Seeding", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-3", title: "Tree Pruning", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-4", title: "Planting", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-5", title: "Mulching", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-6", title: "Landscape Rocks", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-7", title: "Edging", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-8", title: "Garden Beds", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-9", title: "Hedge", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-10", title: "Walkway and Path", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-11", title: "Water Features", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-12", title: "Irrigation System", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-13", title: "Drainage", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "20-14", title: "Greenhouses", section: OUTDOOR_SERVICE_SECTIONS.LANDSCAPING },
  { id: "22-1", title: "Grills", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-2", title: "Outdoor Kitchen", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-3", title: "Fire Pit", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-4", title: "Fireplace", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-5", title: "Patio Heater", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-6", title: "Hot Tubs", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-7", title: "Pool", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-8", title: "Refrigeration", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "22-9", title: "Outdoor Cooling", section: INDOOR_SERVICE_SECTIONS.APPLIANCE },
  { id: "23-1", title: "Wood Siding", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-2", title: "Vinyl Siding", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-3", title: "Brick Veneer", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-4", title: "Stone Cladding", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-5", title: "Stucco", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-6", title: "Metal Cladding", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-7", title: "Glass Facades", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-8", title: "Composite Paneling", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-9", title: "Trims and moldings", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-10", title: "Underlayment", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-11", title: "Pest Control", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "23-12", title: "Maintenance", section: OUTDOOR_SERVICE_SECTIONS.FACADE },
  { id: "24-1", title: "CCTV", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
  { id: "24-2", title: "Wireless Cameras", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
  { id: "24-3", title: "Security Alarms", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
  { id: "24-4", title: "Doorbell Cameras", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
  { id: "24-5", title: "Biometric Access", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
  { id: "24-6", title: "Keypad Access", section: OUTDOOR_SERVICE_SECTIONS.OUTDOOR_SECURITY },
];