export const PACKAGES = [
  {
    id: "basic_package",
    title: "Basic Package",
    services: {
      indoor: [
        { id: "1-1-3", title: "Smoke Detector Detach and Reset", quantityPerYear: 1 },
        { id: "7-1-8", title: "Routine Furnace Maintenance", quantityPerYear: 1 },
        { id: "7-2-4", title: "Boiler Regular Maintenance", quantityPerYear: 1 },
        { id: "7-3-4", title: "Heat Pump Regular Maintenance", quantityPerYear: 1 },
        { id: "7-4-6", title: "Mini Split Air Conditioner Routine Maintenance", quantityPerYear: 1 },
      ],
      outdoor: [
        { id: "9-12-1", title: "Outdoor Carpentry Inspection and Assessment", quantityPerYear: 1 },
        { id: "9-12-2", title: "Outdoor Carpentry Pest Prevention", quantityPerYear: 1 },
        { id: "10-1-5", title: "Outdoor Electrical Panel Safety Inspection", quantityPerYear: 1 },
        { id: "11-2-1", title: "Driveway Pressure Washing", quantityPerYear: 1 },
        { id: "11-6-1", title: "Gutter Debris Removal and Pressure Washing", quantityPerYear: 2 },
      ],
    },
    featuredServices: [
      "Smoke Detector Detach and Reset",
      "Boiler Regular Maintenance",
      "Outdoor Carpentry Pest Prevention",
      "Driveway Pressure Washing",
      "Mini Split Air Conditioner Routine Maintenance"
    ]
  },
  {
    id: "enhanced_package",
    title: "Enhanced Package",
    services: {
      indoor: [
        { id: "1-1-3", title: "Smoke Detector Detach and Reset", quantityPerYear: 1 },
        { id: "7-1-8", title: "Routine Furnace Maintenance", quantityPerYear: 1 },
        { id: "7-2-4", title: "Boiler Regular Maintenance", quantityPerYear: 1 },
        { id: "7-3-4", title: "Heat Pump Regular Maintenance", quantityPerYear: 1 },
        { id: "7-4-6", title: "Mini Split Air Conditioner Routine Maintenance", quantityPerYear: 1 },
        { id: "7-6-4", title: "Ventilation System Duct Cleaning and Maintenance", quantityPerYear: 1 },
        { id: "12-2-1", title: "1BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-2", title: "2BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-3", title: "2BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-4", title: "3BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-5", title: "3BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-6", title: "4BED/3BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-7", title: "4BED/4BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-8", title: "4BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-9", title: "5BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "14-8-6", title: "Appliance Water System Diagnostic", quantityPerYear: 1 },
        { id: "14-8-7", title: "Appliance Thermal Diagnostic", quantityPerYear: 1 },
        { id: "14-8-8", title: "Appliance Noise and Vibration Diagnostic", quantityPerYear: 1 },
        { id: "14-8-9", title: "Appliance Connectivity Diagnostic", quantityPerYear: 1 },
        { id: "14-8-10", title: "Appliance Energy Efficiency Diagnostic", quantityPerYear: 1 },
      ],
      outdoor: [
        { id: "9-12-1", title: "Outdoor Carpentry Inspection and Assessment", quantityPerYear: 1 },
        { id: "9-12-2", title: "Outdoor Carpentry Pest Prevention", quantityPerYear: 1 },
        { id: "10-1-5", title: "Outdoor Electrical Panel Safety Inspection", quantityPerYear: 1 },
        { id: "10-7-2", title: "Whole House Generator Maintenance", quantityPerYear: 1 },
        { id: "10-8-3", title: "Outdoor Electrical Seasonal Preparation", quantityPerYear: 1 },
        { id: "11-1-1", title: "Deck and Patio Pressure Washing", quantityPerYear: 1 },
        { id: "11-2-1", title: "Driveway Pressure Washing", quantityPerYear: 1 },
        { id: "11-6-1", title: "Gutter Debris Removal and Pressure Washing", quantityPerYear: 2 },
        { id: "20-1-4", title: "Spring Lawn Revitalization", quantityPerYear: 1 },
        { id: "20-1-5", title: "Autumn Lawn Preparation", quantityPerYear: 1 },
        { id: "20-1-6", title: "Lawn Winterization", quantityPerYear: 1 },
      ],
    },
    featuredServices: [
      "Ventilation System Duct Cleaning and Maintenance",
      "1BED/1BATH General Cleaning",
      "Whole House Generator Maintenance",
      "Deck and Patio Pressure Washing",
      "Appliance Water System Diagnostic"
    ]
  },
  {
    id: "all_inclusive_package",
    title: "All-Inclusive Package",
    services: {
      indoor: [
        { id: "1-1-3", title: "Smoke Detector Detach and Reset", quantityPerYear: 1 },
        { id: "7-1-8", title: "Routine Furnace Maintenance", quantityPerYear: 1 },
        { id: "7-2-4", title: "Boiler Regular Maintenance", quantityPerYear: 1 },
        { id: "7-3-4", title: "Heat Pump Regular Maintenance", quantityPerYear: 1 },
        { id: "7-4-6", title: "Mini Split Air Conditioner Routine Maintenance", quantityPerYear: 1 },
        { id: "7-6-4", title: "Ventilation System Duct Cleaning and Maintenance", quantityPerYear: 1 },
        { id: "7-10-4", title: "Humidifier/Dehumidifier Maintenance", quantityPerYear: 1 },
        { id: "12-1-1", title: "1BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-2", title: "2BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-3", title: "2BED/2BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-4", title: "3BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-5", title: "3BED/2BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-6", title: "4BED/3BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-7", title: "4BED/4BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-8", title: "4BED/5BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-9", title: "5BED/5BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-2-1", title: "1BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-2", title: "2BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-3", title: "2BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-4", title: "3BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-5", title: "3BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-6", title: "4BED/3BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-7", title: "4BED/4BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-8", title: "4BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-9", title: "5BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-3-1", title: "Fireplace Chimney Sweep Cleaning and Service", quantityPerYear: 1 },
        { id: "12-3-3", title: "Carpet Stairs Cleaning", quantityPerYear: 1 },
        { id: "12-3-4", title: "Tile – Heavy Cleaning", quantityPerYear: 1 },
        { id: "12-3-5", title: "Natural Marble – Heavy Cleaning", quantityPerYear: 1 },
        { id: "12-4-1", title: "Window Cleaning (per side)", quantityPerYear: 1 },
        { id: "14-7-1", title: "Range Hood Cleaning and Maintenance", quantityPerYear: 1 },
      ],
      outdoor: [
        { id: "9-12-1", title: "Outdoor Carpentry Inspection and Assessment", quantityPerYear: 1 },
        { id: "9-12-2", title: "Outdoor Carpentry Pest Prevention", quantityPerYear: 1 },
        { id: "9-12-5", title: "Outdoor Carpentry Winter Prep", quantityPerYear: 1 },
        { id: "10-1-5", title: "Outdoor Electrical Panel Safety Inspection", quantityPerYear: 1 },
        { id: "10-7-2", title: "Whole House Generator Maintenance", quantityPerYear: 1 },
        { id: "10-8-2", title: "Electrical Panel and Circuit Breakers Inspection", quantityPerYear: 1 },
        { id: "10-8-3", title: "Outdoor Electrical Seasonal Preparation", quantityPerYear: 1 },
        { id: "10-10-3", title: "Outdoor Electrical Wiring Maintenance", quantityPerYear: 1 },
        { id: "11-1-1", title: "Deck and Patio Pressure Washing", quantityPerYear: 1 },
        { id: "11-1-2", title: "Deck and Patio Soft Washing", quantityPerYear: 1 },
        { id: "11-2-1", title: "Driveway Pressure Washing", quantityPerYear: 1 },
        { id: "11-3-1", title: "Hot Tub Regular Cleaning", quantityPerYear: 1 },
        { id: "11-5-1", title: "Fence Pressure Washing", quantityPerYear: 1 },
        { id: "11-6-1", title: "Gutter Debris Removal and Pressure Washing", quantityPerYear: 1 },
        { id: "11-8-1", title: "Exterior Lighting Fixture Cleaning", quantityPerYear: 1 },
        { id: "11-8-2", title: "Exterior Decorative Element Cleaning", quantityPerYear: 1 },
        { id: "11-8-3", title: "Exterior Decoration Element Washing", quantityPerYear: 1 },
        { id: "11-9-1", title: "Regular Outdoor Pool Cleaning", quantityPerYear: 1 },
        { id: "11-9-3", title: "Pool Filter and Equipment Maintenance", quantityPerYear: 1 },
        { id: "11-10-1", title: "Garage Door Cleaning", quantityPerYear: 1 },
        { id: "18-7-1", title: "Christmas Lights Installation on a One-Story Building", quantityPerYear: 1 },
        { id: "18-7-2", title: "Roofline and Eaves Installation on a 2-3 Story Building", quantityPerYear: 1 },
        { id: "18-7-3", title: "Christmas Tree and Shrub Wrapping", quantityPerYear: 1 },
        { id: "18-7-4", title: "Large Tree and Shrub Wrapping", quantityPerYear: 1 },
        { id: "18-7-5", title: "Christmas Lights Installation from Customer Materials (Labor)", quantityPerYear: 1 },
        { id: "18-7-6", title: "Christmas Lights Removal", quantityPerYear: 1 },
        { id: "18-8-3", title: "Outdoor Electrical System Maintenance", quantityPerYear: 1 },
        { id: "19-8-1", title: "Roof Ventilation Cleaning", quantityPerYear: 1 },
        { id: "20-1-1", title: "Regular Lawn Mowing", quantityPerYear: 1 },
        { id: "20-1-3", title: "Lawn Aeration and Scarifying", quantityPerYear: 1 },
        { id: "20-1-4", title: "Spring Lawn Revitalization", quantityPerYear: 1 },
        { id: "20-1-5", title: "Autumn Lawn Preparation", quantityPerYear: 1 },
        { id: "20-1-6", title: "Lawn Winterization", quantityPerYear: 1 },
        { id: "20-3-4", title: "Tree Stump Grinding", quantityPerYear: 1 },
        { id: "20-9-2", title: "Hedge Pruning", quantityPerYear: 1 },
        { id: "20-11-3", title: "Ponds and Fountains Maintenance", quantityPerYear: 1 },
        { id: "20-12-16", title: "Irrigation System Maintenance", quantityPerYear: 1 },
        { id: "22-1-2", title: "Outdoor Grill Cleaning", quantityPerYear: 1 },
        { id: "22-5-1", title: "Outdoor Kitchen Cleaning", quantityPerYear: 1 },
      ],
    },
    featuredServices: [
      "Humidifier/Dehumidifier Maintenance",
      "Regular Outdoor Pool Cleaning",
      "Outdoor Electrical Wiring Maintenance",
      "4BED/4BATH Regular Cleaning",
      "Fence Pressure Washing"
    ]
  },
  {
    id: "configure_your_own_package",
    title: "Custom Package",
    services: {
      indoor: [
        { id: "1-1-3", title: "Smoke Detector Detach and Reset", quantityPerYear: 1 },
        { id: "7-1-8", title: "Routine Furnace Maintenance", quantityPerYear: 1 },
        { id: "7-2-4", title: "Boiler Regular Maintenance", quantityPerYear: 1 },
        { id: "7-3-4", title: "Heat Pump Regular Maintenance", quantityPerYear: 1 },
        { id: "7-4-6", title: "Mini Split Air Conditioner Routine Maintenance", quantityPerYear: 1 },
        { id: "7-6-4", title: "Ventilation System Duct Cleaning and Maintenance", quantityPerYear: 1 },
        { id: "7-10-4", title: "Humidifier/Dehumidifier Maintenance", quantityPerYear: 1 },
        { id: "12-1-1", title: "1BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-2", title: "2BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-3", title: "2BED/2BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-4", title: "3BED/1BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-5", title: "3BED/2BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-6", title: "4BED/3BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-7", title: "4BED/4BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-8", title: "4BED/5BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-1-9", title: "5BED/5BATH Regular Cleaning", quantityPerYear: 1 },
        { id: "12-2-1", title: "1BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-2", title: "2BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-3", title: "2BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-4", title: "3BED/1BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-5", title: "3BED/2BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-6", title: "4BED/3BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-7", title: "4BED/4BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-8", title: "4BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-2-9", title: "5BED/5BATH General Cleaning", quantityPerYear: 1 },
        { id: "12-3-1", title: "Fireplace Chimney Sweep Cleaning and Service", quantityPerYear: 1 },
        { id: "12-3-3", title: "Carpet Stairs Cleaning", quantityPerYear: 1 },
        { id: "12-3-4", title: "Tile - Heavy Cleaning", quantityPerYear: 1 },
        { id: "12-3-5", title: "Natural Marble - Heavy Cleaning", quantityPerYear: 1 },
        { id: "12-4-1", title: "Window Cleaning (per side)", quantityPerYear: 1 },
        { id: "14-7-1", title: "Range Hood Cleaning and Maintenance", quantityPerYear: 1 },
        { id: "14-8-6", title: "Appliance Water System Diagnostic", quantityPerYear: 1 },
        { id: "14-8-7", title: "Appliance Thermal Diagnostic", quantityPerYear: 1 },
        { id: "14-8-8", title: "Appliance Noise and Vibration Diagnostic", quantityPerYear: 1 },
        { id: "14-8-9", title: "Appliance Connectivity Diagnostic", quantityPerYear: 1 },
        { id: "14-8-10", title: "Appliance Energy Efficiency Diagnostic", quantityPerYear: 1 },
        { id: "15-3-2", title: "Smart Lock Maintenance and Troubleshooting", quantityPerYear: 1 },
        { id: "17-4-1", title: "Wood Furniture Cleaning", quantityPerYear: 1 },
        { id: "17-4-2", title: "Stainless Steel Furniture Cleaning", quantityPerYear: 1 },
        { id: "17-4-3", title: "Copper and Brass Furniture Cleaning", quantityPerYear: 1 },
        { id: "17-4-4", title: "Metal and Cast Iron Furniture Cleaning", quantityPerYear: 1 },
        { id: "17-6-1", title: "Leather Upholstery Cleaning", quantityPerYear: 1 },
        { id: "17-6-2", title: "Fabric Upholstery Cleaning", quantityPerYear: 1 },
        { id: "17-6-3", title: "Upholstery Repair", quantityPerYear: 1 },
      ],
      outdoor: [
        { id: "9-12-1", title: "Outdoor Carpentry Inspection and Assessment", quantityPerYear: 1 },
        { id: "9-12-2", title: "Outdoor Carpentry Pest Prevention", quantityPerYear: 1 },
        { id: "9-12-5", title: "Outdoor Carpentry Winter Prep", quantityPerYear: 1 },
        { id: "10-1-5", title: "Outdoor Electrical Panel Safety Inspection", quantityPerYear: 1 },
        { id: "10-7-2", title: "Whole House Generator Maintenance", quantityPerYear: 1 },
        { id: "10-8-2", title: "Electrical Panel and Circuit Breakers Inspection", quantityPerYear: 1 },
        { id: "10-8-3", title: "Outdoor Electrical Seasonal Preparation", quantityPerYear: 1 },
        { id: "10-10-3", title: "Outdoor Electrical Wiring Maintenance", quantityPerYear: 1 },
        { id: "11-1-1", title: "Deck and Patio Pressure Washing", quantityPerYear: 1 },
        { id: "11-1-2", title: "Deck and Patio Soft Washing", quantityPerYear: 1 },
        { id: "11-2-1", title: "Driveway Pressure Washing", quantityPerYear: 1 },
        { id: "11-3-1", title: "Hot Tub Regular Cleaning", quantityPerYear: 1 },
        { id: "11-5-1", title: "Fence Pressure Washing", quantityPerYear: 1 },
        { id: "11-6-1", title: "Gutter Debris Removal and Pressure Washing", quantityPerYear: 1 },
        { id: "11-8-1", title: "Exterior Lighting Fixture Cleaning", quantityPerYear: 1 },
        { id: "11-8-2", title: "Exterior Decorative Element Cleaning", quantityPerYear: 1 },
        { id: "11-8-3", title: "Exterior Decoration Element Washing", quantityPerYear: 1 },
        { id: "11-9-1", title: "Regular Outdoor Pool Cleaning", quantityPerYear: 1 },
        { id: "11-9-3", title: "Pool Filter and Equipment Maintenance", quantityPerYear: 1 },
        { id: "11-10-1", title: "Garage Door Cleaning", quantityPerYear: 1 },
        { id: "18-7-1", title: "Christmas Lights Installation on a One-Story Building", quantityPerYear: 1 },
        { id: "18-7-2", title: "Roofline and Eaves Installation on a 2-3 Story Building", quantityPerYear: 1 },
        { id: "18-7-3", title: "Christmas Tree and Shrub Wrapping", quantityPerYear: 1 },
        { id: "18-7-4", title: "Large Tree and Shrub Wrapping", quantityPerYear: 1 },
        { id: "18-7-5", title: "Christmas Lights Installation from Customer Materials (Labor)", quantityPerYear: 1 },
        { id: "18-7-6", title: "Christmas Lights Removal", quantityPerYear: 1 },
        { id: "18-8-3", title: "Outdoor Electrical System Maintenance", quantityPerYear: 1 },
        { id: "19-8-1", title: "Roof Ventilation Cleaning", quantityPerYear: 1 },
        { id: "20-1-1", title: "Regular Lawn Mowing", quantityPerYear: 1 },
        { id: "20-1-2", title: "Lawn Edging and Trimming", quantityPerYear: 1 },
        { id: "20-1-3", title: "Lawn Aeration and Scarifying", quantityPerYear: 1 },
        { id: "20-1-4", title: "Spring Lawn Revitalization", quantityPerYear: 1 },
        { id: "20-1-5", title: "Autumn Lawn Preparation", quantityPerYear: 1 },
        { id: "20-1-6", title: "Lawn Winterization", quantityPerYear: 1 },
        { id: "20-3-2", title: "Tree Pruning", quantityPerYear: 1 },
        { id: "20-3-3", title: "Tree Formative Pruning", quantityPerYear: 1 },
        { id: "20-3-4", title: "Tree Stump Grinding", quantityPerYear: 1 },
        { id: "20-9-2", title: "Hedge Pruning", quantityPerYear: 1 },
        { id: "20-11-3", title: "Ponds and Fountains Maintenance", quantityPerYear: 1 },
        { id: "20-12-5", title: "Irrigation System Winterization", quantityPerYear: 1 },
        { id: "20-12-6", title: "Irrigation System Spring Activation", quantityPerYear: 1 },
        { id: "20-12-16", title: "Irrigation System Maintenance", quantityPerYear: 1 },
        { id: "22-1-2", title: "Outdoor Grill Cleaning", quantityPerYear: 1 },
        { id: "22-5-1", title: "Outdoor Kitchen Cleaning", quantityPerYear: 1 },
        { id: "22-4-2", title: "Fire Pit Cleaning", quantityPerYear: 1 },
        { id: "22-7-1", title: "Pool Cleaning", quantityPerYear: 1 },
        { id: "22-8-3", title: "Outdoor Refrigeration System Maintenance", quantityPerYear: 1 },
      ],
    },
    featuredServices: [
      "Fireplace Chimney Sweep Cleaning and Service",
      "Outdoor Grill Cleaning",
      "Pool Filter and Equipment Maintenance",
      "Tree Stump Grinding",
      "Stainless Steel Furniture Cleaning"
    ]
  }
];
