export const ROOMS = {
  indoor: [
    {
      id: "attic",
      title: "Attic",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-9", title: "Motion Sensor Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        {
          id: "1-6-2",
          title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)",
        },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "1-7-2", title: "Crystal Chandelier Installation" },
        { id: "1-7-3", title: "Chandelier Detach and Reset (up to 6 lights)" },
        {
          id: "1-7-4",
          title: "Chandelier Detach and Reset (more than 6 lights)",
        },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        {
          id: "3-4-1",
          title: "White Trim and Molding Painting (One Coat Refresh)",
        },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        {
          id: "3-5-2",
          title: "White Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        {
          id: "3-5-4",
          title: "Color Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        {
          id: "3-6-2",
          title: "White Window Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        {
          id: "3-6-4",
          title: "Color Window Painting (Two Sides, Jamb, and Trim)",
        },
      ],
    },
    {
      id: "basement",
      title: "Basement",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-9", title: "Motion Sensor Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        {
          id: "1-6-2",
          title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)",
        },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "1-8-2", title: "Wiring Installation (no conduits)" },
        { id: "1-8-3", title: "Wiring with Metal Conduit Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-6", title: "Concrete and Masonry Wall Painting" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        {
          id: "3-4-1",
          title: "White Trim and Molding Painting (One Coat Refresh)",
        },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        {
          id: "3-5-2",
          title: "White Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        {
          id: "3-5-4",
          title: "Color Door Painting (Two Sides, Jamb, and Trim)",
        },
        {
          id: "3-5-5",
          title: "Door Staining and Finishing (One Side, Jamb, and Trim)",
        },
        {
          id: "3-5-6",
          title: "Door Staining and Finishing (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        {
          id: "3-6-2",
          title: "White Window Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        {
          id: "3-6-4",
          title: "Color Window Painting (Two Sides, Jamb, and Trim)",
        },
        {
          id: "3-6-5",
          title: "Window Staining and Finishing (One Side, Jamb, and Trim)",
        },
        {
          id: "3-6-6",
          title: "Window Staining and Finishing (Two Sides, Jamb, and Trim)",
        },
        { id: "3-9-1", title: "Concrete and Masonry Painting (Two Coats)" },
        { id: "3-9-2", title: "Block Sealing" },
        { id: "3-9-3", title: "Mold Removal and Wall Protection" },
        { id: "3-10-1", title: "Baseboard Painting" },
        { id: "3-10-2", title: "Baseboard Staining and Finishing" },
        { id: "4-3-1", title: "Natural Stone Removal" },
        { id: "4-3-2", title: "Wall Veneer Panels Installation" },
        { id: "4-3-3", title: "Natural Stone Tile Installation" },
        { id: "4-3-4", title: "Natural Stone Sill Installation" },
        { id: "4-3-5", title: "Natural Stone Threshold Installation" },
        { id: "4-3-6", title: "Natural Stone Countertop Installation" },
        { id: "4-8-1", title: "Leveling with Cement" },
        { id: "4-8-2", title: "Mortar Bed Preparation for Tile Floors" },
        { id: "4-8-3", title: "Mortar Bed Removal" },
        { id: "4-8-4", title: "Mortar Bed Preparation for Tile Walls" },
        { id: "4-8-5", title: "Uncoupling Mat for Tile Installation" },
        { id: "4-8-6", title: "Cement Board Installation" },
        { id: "5-3-1", title: "Vinyl Tile Removal" },
        { id: "5-3-2", title: "Vinyl Tile Installation" },
        { id: "5-3-3", title: "Self-Adhesive Vinyl Tile Installation" },
        { id: "5-4-1", title: "Vinyl Covering Removal" },
        { id: "5-4-2", title: "Vinyl Covering Installation" },
        { id: "5-4-3", title: "Vinyl Plank Installation" },
        { id: "5-4-4", title: "Vinyl Stair Tread Installation" },
      ],
    },
    {
      id: "bathroom",
      title: "Bathroom",
      activities: [
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-8", title: "Humidity Sensor Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "2-1-1", title: "Toilet Supply and Installation" },
        { id: "2-1-6", title: "Urinal Installation" },
        { id: "2-1-7", title: "Smart Toilet Bidet Installation" },
        { id: "2-1-8", title: "Electric Bidet Seat Installation" },
        { id: "2-2-1", title: "Faucet Replacement" },
        { id: "2-2-2", title: "Rectangular Tub/Shower Combo Installation" },
        { id: "2-2-3", title: "Shower Base Replacement" },
        { id: "2-2-4", title: "Shower Walls Replacement" },
        { id: "2-2-5", title: "Sliding Shower Door Installation" },
        { id: "2-3-1", title: "Freestanding Bathtub and Faucet Installation" },
        { id: "2-3-2", title: "Alcove Bathtub Installation" },
        { id: "2-3-3", title: "Tub Surrounds Installation" },
        { id: "2-3-4", title: "Sliding Bathtub Door Installation" },
        { id: "2-4-1", title: "Vessel Sink Installation" },
        { id: "2-4-2", title: "Undermount Sink Installation" },
        { id: "2-4-3", title: "Pedestal Sink Installation" },
        { id: "2-4-4", title: "Wall Mount Sink Installation" },
        { id: "2-4-5", title: "Old Sink Removal" },
        { id: "2-5-1", title: "Vessel Sink Faucet Installation" },
        { id: "2-5-2", title: "Undermount Sink Faucet Installation" },
        { id: "2-5-3", title: "Pedestal Sink Faucet Installation" },
        { id: "2-5-4", title: "Single Hole Faucet Installation" },
        { id: "2-5-7", title: "Bidet Sprayer Installation" },
        { id: "3-1-4", title: "Bathroom Wall Painting (White)" },
        { id: "3-1-5", title: "Bathroom Wall Painting (Color)" },
        { id: "3-1-6", title: "Concrete and Masonry Wall Painting" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        {
          id: "3-5-2",
          title: "White Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        {
          id: "3-5-4",
          title: "Color Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "3-9-3", title: "Mold Removal and Wall Protection" },
        { id: "4-1-1", title: "Ceramic Tile Removal" },
        { id: "4-1-2", title: "Ceramic Tile Installation" },
        { id: "4-1-3", title: "Ceramic Tile Repair" },
        { id: "4-1-4", title: "Ceramic Tile Customization" },
        { id: "4-1-5", title: "Ceramic Tile Regrouting" },
        { id: "4-10-1", title: "Floor Heating Mat Installation" },
        { id: "4-2-1", title: "Porcelain Tile Removal" },
        { id: "4-2-2", title: "Porcelain Tile Installation" },
        { id: "4-2-3", title: "Porcelain Tile Repair" },
        { id: "4-2-4", title: "Porcelain Tile Customization" },
        { id: "4-2-5", title: "Porcelain Tile Regrouting" },
        { id: "4-3-1", title: "Natural Stone Removal" },
        { id: "4-3-2", title: "Wall Veneer Panels Installation" },
        { id: "4-3-3", title: "Natural Stone Tile Installation" },
        { id: "4-3-4", title: "Natural Stone Sill Installation" },
        { id: "4-3-5", title: "Natural Stone Threshold Installation" },
        { id: "4-3-6", title: "Natural Stone Countertop Installation" },
        { id: "4-3-7", title: "Cut for Sink Opening in Natural Marble" },
        { id: "4-3-8", title: "Natural Stone Mosaic Installation" },
        { id: "4-4-1", title: "Marble Mosaic Installation" },
        { id: "4-4-2", title: "Glass Mosaic Installation" },
        { id: "4-4-3", title: "Porcelain Mosaic Installation" },
        { id: "4-4-4", title: "Mosaic Removal" },
        { id: "4-5-1", title: "Bathroom Demolition and Removal" },
        {
          id: "4-5-2",
          title: "Waterproofing and Tile Shower Installation (up to 60 SF)",
        },
        {
          id: "4-5-3",
          title: "Waterproofing and Tile Shower Installation (61 to 100 SF)",
        },
        { id: "4-5-6", title: "Bathroom Mirror Installation" },
        { id: "5-7-1", title: "Wood Floor Sanding, Staining, and Finishing" },
        { id: "6-7-5", title: "Glass Block Window Installation" },
        { id: "6-7-7", title: "Skylight Installation" },
        { id: "7-6-1", title: "Bathroom Ventilation Fan Removal" },
        { id: "7-6-2", title: "Bathroom Ventilation Fan Installation" },
        { id: "13-7-1", title: "Smooth Drywall Finishing" },
        { id: "17-2-4", title: "Frameless Mirror Hanging Installation" },
      ],
    },
    {
      id: "bedroom",
      title: "Bedroom",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-4", title: "Phone, TV, or Speaker Outlet Installation" },
        { id: "1-5-5", title: "Floor Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        {
          id: "1-6-2",
          title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)",
        },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "1-7-2", title: "Crystal Chandelier Installation" },
        { id: "1-7-3", title: "Chandelier Detach and Reset (up to 6 lights)" },
        {
          id: "1-7-4",
          title: "Chandelier Detach and Reset (more than 6 lights)",
        },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        {
          id: "3-4-1",
          title: "White Trim and Molding Painting (One Coat Refresh)",
        },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        {
          id: "3-5-2",
          title: "White Door Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        {
          id: "3-5-4",
          title: "Color Door Painting (Two Sides, Jamb, and Trim)",
        },
        {
          id: "3-5-5",
          title: "Door Staining and Finishing (One Side, Jamb, and Trim)",
        },
        {
          id: "3-5-6",
          title: "Door Staining and Finishing (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        {
          id: "3-6-2",
          title: "White Window Painting (Two Sides, Jamb, and Trim)",
        },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        {
          id: "3-6-4",
          title: "Color Window Painting (Two Sides, Jamb, and Trim)",
        },
        {
          id: "3-6-5",
          title: "Window Staining and Finishing (One Side, Jamb, and Trim)",
        },
        {
          id: "3-6-6",
          title: "Window Staining and Finishing (Two Sides, Jamb, and Trim)",
        },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "3-8-3", title: "Fabric Wallpaper Installation" },
        { id: "3-8-4", title: "Sisal Wallpaper Installation" },
        { id: "3-8-5", title: "Border Installation" },
        { id: "3-8-6", title: "Paintable Wallpaper Installation" },
        { id: "4-1-1", title: "Ceramic Tile Removal" },
        { id: "4-7-1", title: "Fireplace Hearth Tile Installation" },
        { id: "5-1-1", title: "Carpet Removal" },
        { id: "6-6-1", title: "Interior Door Removal" },
        { id: "17-2-1", title: "Shelf Mounting" },
        { id: "17-7-1", title: "Large Furniture Removal" },
      ],
    },
    {
      id: "garage",
      title: "Garage",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-9", title: "Motion Sensor Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-2", title: "30 Amp Outlet Installation" },
        { id: "1-5-3", title: "50 Amp Outlet Installation" },
        { id: "1-5-4", title: "Phone, TV, or Speaker Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        { id: "1-6-2", title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)" },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "1-8-3", title: "Wiring with Metal Conduit Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-6", title: "Concrete and Masonry Wall Painting" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "4-1-1", title: "Ceramic Tile Removal" },
        { id: "4-8-1", title: "Leveling with Cement" },
        { id: "6-1-2", title: "Full Height Cabinet Removal" },
        { id: "6-6-8", title: "8-9 Foot Garage Door Installation" },
        { id: "6-6-9", title: "16 Foot Garage Door Installation" },
        { id: "6-6-10", title: "Garage Door Repair" },
        { id: "7-9-4", title: "Garage Air Heater Installation" },
        { id: "15-7-2", title: "Garage Door Safety Sensors Installation" },
        { id: "17-5-1", title: "Garage Storage Installation" },
        { id: "21-1-6", title: "Garage Move" },
      ],
    },
    {
      id: "home_cinema",
      title: "Home Cinema",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-2", title: "White Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-6-4", title: "Color Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "5-1-1", title: "Carpet Removal" },
        { id: "5-1-3", title: "Carpet Tile Installation" },
        { id: "5-3-1", title: "Vinyl Tile Removal" },
        { id: "5-3-2", title: "Vinyl Tile Installation" },
        { id: "5-4-1", title: "Vinyl Covering Removal" },
        { id: "5-4-2", title: "Vinyl Covering Installation" },
        { id: "13-1-1", title: "Drywall Repair (Up to 4 Square Feet)" },
        { id: "13-2-1", title: "Machine Texturing for Drywall" },
        { id: "13-3-1", title: "Acoustic Drywall Installation" },
        { id: "16-1-1", title: "Built-in Theater Projector Installation" },
        { id: "16-3-1", title: "Theater Sound System Installation" },
        { id: "16-7-1", title: "TV Panel Installation (Up to 64')" },
        { id: "16-7-2", title: "TV Panel Installation (Up to 90')" },
        { id: "16-9-1", title: "Studiofoam Wedges Installation" },
        { id: "16-9-2", title: "Paintable Sound Absorbing Acoustic Panels Installation" },
        { id: "17-2-4", title: "Frameless Mirror Hanging Installation" },
        { id: "17-2-5", title: "Framed Mirror Hanging" },
      ],
    },
    {
      id: "homeoffice",
      title: "Home Office",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-4", title: "Phone, TV, or Speaker Outlet Installation" },
        { id: "1-5-5", title: "Floor Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        { id: "1-6-2", title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "1-7-2", title: "Crystal Chandelier Installation" },
        { id: "1-7-3", title: "Chandelier Detach and Reset (up to 6 lights)" },
        { id: "1-7-4", title: "Chandelier Detach and Reset (more than 6 lights)" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-2", title: "White Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-6-4", title: "Color Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "5-1-1", title: "Carpet Removal" },
        { id: "6-1-2", title: "Full Height Cabinet Removal" },
        { id: "6-1-3", title: "Upper (Wall) or Lower (Base) Cabinet Installation" },
        { id: "16-1-1", title: "Built-in Theater Projector Installation" },
        { id: "16-3-1", title: "Theater Sound System Installation" },
        { id: "17-1-1", title: "Flat-Pack Furniture Assembly (Small and Medium Items)" },
        { id: "17-2-1", title: "Shelf Mounting" },
        { id: "17-3-2", title: "Cabinet Mechanism Repairs" },
      ],
    },
    {
      id: "kitchen",
      title: "Kitchen",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-9", title: "Motion Sensor Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-2", title: "30 Amp Outlet Installation" },
        { id: "1-5-3", title: "50 Amp Outlet Installation" },
        { id: "1-5-4", title: "Phone, TV, or Speaker Outlet Installation" },
        { id: "1-5-5", title: "Floor Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        { id: "1-6-2", title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)" },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "1-7-2", title: "Crystal Chandelier Installation" },
        { id: "1-7-3", title: "Chandelier Detach and Reset (up to 6 lights)" },
        { id: "1-7-4", title: "Chandelier Detach and Reset (more than 6 lights)" },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "2-4-6", title: "Undermount Kitchen Sink Installation" },
        { id: "2-4-7", title: "Double Basin Sink Installation" },
        { id: "2-5-5", title: "Kitchen Faucet Installation" },
        { id: "2-5-6", title: "Wall Mounted Potfiller Installation" },
        { id: "2-7-1", title: "Garbage Disposal Installation" },
        { id: "2-7-2", title: "Garbage Disposal Removal" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-5", title: "Door Staining and Finishing (One Side, Jamb, and Trim)" },
        { id: "3-5-6", title: "Door Staining and Finishing (Two Sides, Jamb, and Trim)" },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-2", title: "White Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-6-4", title: "Color Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "4-3-7", title: "Cut for Sink Opening in Natural Marble" },
        { id: "4-6-1", title: "Countertop Tile Installation" },
        { id: "4-6-2", title: "Tile Backsplash Installation" },
        { id: "4-6-3", title: "Natural Stone Countertop Installation" },
        { id: "4-6-4", title: "Solid Surface Countertop Installation" },
        { id: "4-6-5", title: "Floor Tile Installation" },
        { id: "4-6-6", title: "Tile Floor Regrouting" },
        { id: "4-10-1", title: "Floor Heating Mat Installation" },
        { id: "5-3-1", title: "Vinyl Tile Removal" },
        { id: "6-1-3", title: "Upper (Wall) or Lower (Base) Cabinet Installation" },
        { id: "6-10-1", title: "Butcher Block Countertop Installation" },
        { id: "6-10-4", title: "Laminate Countertop Installation" },
        { id: "14-1-1", title: "Refrigerator Removal" },
        { id: "14-2-2", title: "Freestanding Gas Range Installation" },
        { id: "14-3-2", title: "Dishwasher Installation" },
        { id: "15-1-1", title: "Fire Alarm Detector Installation" },
        { id: "17-2-1", title: "Shelf Mounting" },
        { id: "21-1-2", title: "Kitchen Move" },
      ],
    },
    {
      id: "laundry",
      title: "Laundry",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-4-8", title: "Humidity Sensor Installation" },
        { id: "1-4-9", title: "Motion Sensor Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-2", title: "30 Amp Outlet Installation" },
        { id: "1-5-3", title: "50 Amp Outlet Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "2-4-1", title: "Vessel Sink Installation" },
        { id: "2-4-2", title: "Undermount Sink Installation" },
        { id: "2-4-3", title: "Pedestal Sink Installation" },
        { id: "2-4-4", title: "Wall Mount Sink Installation" },
        { id: "2-4-5", title: "Old Sink Removal" },
        { id: "2-4-6", title: "Undermount Kitchen Sink Installation" },
        { id: "2-5-1", title: "Vessel Sink Faucet Installation" },
        { id: "2-5-2", title: "Undermount Sink Faucet Installation" },
        { id: "2-5-3", title: "Pedestal Sink Faucet Installation" },
        { id: "2-5-4", title: "Single Hole Faucet Installation" },
        { id: "2-8-1", title: "Drain Line Camera Inspection" },
        { id: "2-8-2", title: "Clog Clearing" },
        { id: "3-1-4", title: "Bathroom Wall Painting (White)" },
        { id: "3-1-5", title: "Bathroom Wall Painting (Color)" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-7-1", title: "Full Height Cabinet Strip and Refinish (Faces Only)" },
        { id: "3-7-2", title: "Lower/Upper Cabinet Strip and Refinish (Faces Only)" },
        { id: "3-9-1", title: "Concrete and Masonry Painting (Two Coats)" },
        { id: "3-9-2", title: "Block Sealing" },
        { id: "3-9-3", title: "Mold Removal and Wall Protection" },
        { id: "4-1-1", title: "Ceramic Tile Removal" },
        { id: "4-1-2", title: "Ceramic Tile Installation" },
        { id: "4-1-4", title: "Ceramic Tile Customization" },
        { id: "6-1-1", title: "Full Height Cabinet Detachment and Resetting" },
        { id: "6-1-2", title: "Full Height Cabinet Removal" },
        { id: "6-1-3", title: "Upper (Wall) or Lower (Base) Cabinet Installation" },
        { id: "6-1-4", title: "Cabinet Drawer Front Installation" },
        { id: "6-1-5", title: "Cabinetry Restoration and Repair" },
        { id: "6-6-1", title: "Interior Door Removal" },
        { id: "6-6-2", title: "Interior Door Installation" },
        { id: "7-6-4", title: "Ventilation System Duct Cleaning and Maintenance" },
        { id: "12-6-3", title: "Final Cleaning after Construction" },
        { id: "13-1-1", title: "Drywall Repair (Up to 4 Square Feet)" },
        { id: "13-1-2", title: "Drywall Repair (Holes & Cracks Up to 3 Inches)" },
        { id: "13-1-3", title: "Corner Bead Repair" },
        { id: "14-4-1", title: "Washer Removal" },
        { id: "14-4-2", title: "Smart Washer Installation" },
        { id: "14-4-3", title: "Laundry Center Installation" },
        { id: "14-5-1", title: "Dryer Removal" },
        { id: "14-5-2", title: "Electric Dryer Installation" },
        { id: "14-5-3", title: "Gas Dryer Installation" },
        { id: "14-5-4", title: "Dryer Vent Cleaning" },
        { id: "15-8-1", title: "Smart Leak Detectors Installation" },
        { id: "15-8-2", title: "Smart Water Detector and Automatic Water Shutoff Installation" },
        { id: "17-1-1", title: "Flat-Pack Furniture Assembly (Small and Medium Items)" },
        { id: "17-1-2", title: "Flat-Pack Furniture Assembly (Large Items)" },
        { id: "17-2-1", title: "Shelf Mounting" },
        { id: "17-5-1", title: "Garage Storage Installation" },
        { id: "17-5-2", title: "Closet Organizer Installation" },
        { id: "17-5-3", title: "Wire Closet Organizer Installation" },
        { id: "17-5-4", title: "Shelving Installation" },
      ],
    },
    {
      id: "living",
      title: "Living Room",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-10-1", title: "Track Lighting Kit Installation" },
        { id: "1-10-2", title: "Fixed Track Lighting Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "1-5-4", title: "Phone, TV, or Speaker Outlet Installation" },
        { id: "1-5-5", title: "Floor Outlet Installation" },
        { id: "1-6-1", title: "Dimmer Switch Installation" },
        { id: "1-6-2", title: "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)" },
        { id: "1-6-3", title: "Wi-Fi Motion Sensor Dimmer Installation" },
        { id: "1-6-4", title: "Countdown Timer Installation" },
        { id: "1-7-1", title: "Chandelier Installation" },
        { id: "1-7-2", title: "Crystal Chandelier Installation" },
        { id: "1-7-3", title: "Chandelier Detach and Reset (up to 6 lights)" },
        { id: "1-7-4", title: "Chandelier Detach and Reset (more than 6 lights)" },
        { id: "1-8-1", title: "Wiring with PVC Conduit Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-1-6", title: "Concrete and Masonry Wall Painting" },
        { id: "3-1-7", title: "Wall Staining and Finishing" },
        { id: "3-10-1", title: "Baseboard Painting" },
        { id: "3-10-2", title: "Baseboard Staining and Finishing" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-3-1", title: "Popcorn Ceiling Removal" },
        { id: "3-3-2", title: "Popcorn Ceiling Installation" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-5", title: "Door Staining and Finishing (One Side, Jamb, and Trim)" },
        { id: "3-5-6", title: "Door Staining and Finishing (Two Sides, Jamb, and Trim)" },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-2", title: "White Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-6-4", title: "Color Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-5", title: "Window Staining and Finishing (One Side, Jamb, and Trim)" },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "3-8-3", title: "Fabric Wallpaper Installation" },
        { id: "3-8-4", title: "Sisal Wallpaper Installation" },
        { id: "3-8-5", title: "Border Installation" },
        { id: "3-8-6", title: "Paintable Wallpaper Installation" },
        { id: "3-9-1", title: "Concrete and Masonry Painting (Two Coats)" },
        { id: "4-1-1", title: "Ceramic Tile Removal" },
        { id: "4-1-2", title: "Ceramic Tile Installation" },
        { id: "4-1-3", title: "Ceramic Tile Repair" },
        { id: "4-1-4", title: "Ceramic Tile Customization" },
        { id: "4-1-5", title: "Ceramic Tile Regrouting" },
        { id: "5-1-1", title: "Carpet Removal" },
        { id: "5-7-1", title: "Wood Floor Sanding, Staining, and Finishing" },
        { id: "6-6-1", title: "Interior Door Removal" },
        { id: "6-6-2", title: "Interior Door Installation" },
        { id: "13-7-1", title: "Smooth Drywall Finishing" },
        { id: "16-7-1", title: "TV Panel Installation (Up to 64')" },
        { id: "16-7-2", title: "TV Panel Installation (Up to 90')" },
        { id: "21-1-3", title: "Living Room Move" },
        { id: "21-3-3", title: "Living Room Packing and Unpacking" },
        { id: "21-4-1", title: "Piano Move" },
        { id: "21-4-2", title: "Art and Antiques Move" },
        { id: "21-4-3", title: "Chandelier Move" },
      ],
    },
    {
      id: "playroom",
      title: "Playroom",
      activities: [
        { id: "1-1-1", title: "Battery-Operated Smoke Detector Installation" },
        { id: "1-1-2", title: "Hardwired Smoke Detector Installation" },
        { id: "1-2-1", title: "Ceiling Fan Replacement" },
        { id: "1-2-2", title: "Ceiling Fan Removal" },
        { id: "1-3-1", title: "Light Fixture Removal" },
        { id: "1-3-2", title: "Light Fixture Installation" },
        { id: "1-3-3", title: "Wall Sconce Installation" },
        { id: "1-3-4", title: "Recessed Light Installation" },
        { id: "1-4-1", title: "Switch Replacement" },
        { id: "1-4-2", title: "1-Gang Switch Installation" },
        { id: "1-4-3", title: "2-Gang Switch Installation" },
        { id: "1-4-4", title: "3-Gang Switch Installation" },
        { id: "1-4-5", title: "1-Gang Toggle Switch Installation" },
        { id: "1-4-6", title: "2-Gang Toggle Switch Installation" },
        { id: "1-4-7", title: "3-Gang Toggle Switch Installation" },
        { id: "1-5-1", title: "15 Amp Outlet Installation" },
        { id: "3-1-1", title: "White Wall Painting (Two Coats)" },
        { id: "3-1-2", title: "Wall Painting Refresh (One Coat)" },
        { id: "3-1-3", title: "Color Wall Painting (Two Coats)" },
        { id: "3-2-1", title: "Ceiling Painting: Seal, Prime, and Paint" },
        { id: "3-2-2", title: "One Coat Refresh Ceiling Painting" },
        { id: "3-4-1", title: "White Trim and Molding Painting (One Coat Refresh)" },
        { id: "3-4-2", title: "Color Trim and Molding Painting (Two Coats)" },
        { id: "3-4-3", title: "Trim and Molding Staining and Finishing" },
        { id: "3-5-1", title: "White Door Painting (One Side)" },
        { id: "3-5-2", title: "White Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-3", title: "Color Door Painting (One Side)" },
        { id: "3-5-4", title: "Color Door Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-5-5", title: "Door Staining and Finishing (One Side, Jamb, and Trim)" },
        { id: "3-5-6", title: "Door Staining and Finishing (Two Sides, Jamb, and Trim)" },
        { id: "3-6-1", title: "White Window Painting (One Side)" },
        { id: "3-6-2", title: "White Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-3", title: "Color Window Painting (One Side)" },
        { id: "3-6-4", title: "Color Window Painting (Two Sides, Jamb, and Trim)" },
        { id: "3-6-5", title: "Window Staining and Finishing (One Side, Jamb, and Trim)" },
        { id: "3-6-6", title: "Window Staining and Finishing (Two Sides, Jamb, and Trim)" },
        { id: "3-8-1", title: "Wallpaper Removal" },
        { id: "3-8-2", title: "Wallpaper Installation" },
        { id: "3-8-3", title: "Fabric Wallpaper Installation" },
        { id: "3-8-4", title: "Sisal Wallpaper Installation" },
        { id: "3-8-5", title: "Border Installation" },
        { id: "3-8-6", title: "Paintable Wallpaper Installation" },
        { id: "5-1-1", title: "Carpet Removal" },
        { id: "5-1-2", title: "Carpet Installation" },
        { id: "5-1-3", title: "Carpet Tile Installation" },
        { id: "5-1-4", title: "Stairs Carpet Installation" },
        { id: "5-2-1", title: "Carpet Pad Removal" },
        { id: "5-2-2", title: "Carpet Pad Installation" },
        { id: "5-7-1", title: "Wood Floor Sanding, Staining, and Finishing" },
        { id: "5-7-2", title: "Parquet Flooring Removal" },
        { id: "5-8-1", title: "Pre-Finished Solid Wood Flooring Removal" },
        { id: "5-8-2", title: "Pre-finished Solid Wood Installation" },
        { id: "5-8-3", title: "Pre-Finished Solid Wood Floor Repair" },
        { id: "5-9-1", title: "Engineered Wood Removal" },
        { id: "5-9-2", title: "Engineered Wood Floating Floor Installation" },
        { id: "5-9-3", title: "Engineered Wood Glue-Down Floor Installation" },
        { id: "6-1-1", title: "Full Height Cabinet Detachment and Resetting" },
        { id: "6-1-2", title: "Full Height Cabinet Removal" },
        { id: "6-6-1", title: "Interior Door Removal" },
        { id: "6-6-2", title: "Interior Door Installation" },
        { id: "6-6-6", title: "Pocket Door Installation" },
        { id: "6-6-7", title: "Sliding Closet Door Installation" },
        { id: "6-7-1", title: "Window Reglazing (up to 24x36 inches)" },
        { id: "6-7-2", title: "Aluminum Window Installation (up to 40 square feet)" },
        { id: "6-7-3", title: "Vinyl Window Installation (up to 40 square feet)" },
        { id: "6-7-4", title: "Wood Window Installation (up to 40 square feet)" },
        { id: "6-9-1", title: "Overlapping Wainscot Installation" },
        { id: "6-9-2", title: "Beadboard Panel Installation" },
        { id: "6-9-3", title: "Shiplap Board Installation" },
        { id: "6-9-4", title: "Decorative Panels Installation" },
        { id: "6-9-5", title: "Wood Panel Removal" },
        { id: "7-4-1", title: "Mini Split Air Conditioner Removal" },
        { id: "7-4-2", title: "Mini Split Air Conditioner Installation" },
        { id: "7-4-3", title: "2 Zone Mini Split Air Conditioner Installation" },
        { id: "12-6-3", title: "Final Cleaning after Construction" },
        { id: "17-1-1", title: "Flat-Pack Furniture Assembly (Small and Medium Items)" },
        { id: "17-1-2", title: "Flat-Pack Furniture Assembly (Large Items)" },
        { id: "17-1-5", title: "Children's Simple Furniture Assembly" },
        { id: "17-1-6", title: "Children's Playsets Assembly" },
        { id: "17-2-1", title: "Shelf Mounting" },
        { id: "17-2-2", title: "Small and Medium Picture Hanging Installation" },
        { id: "17-5-2", title: "Closet Organizer Installation" },
        { id: "17-5-3", title: "Wire Closet Organizer Installation" },
        { id: "17-5-4", title: "Shelving Installation" },
      ],
    }
  ],
  outdoor: [
    {
      id: "driveway",
      title: "Driveway",
      activities: [
        { id: "8-10-1", title: "Concrete Epoxy Painting" },
        { id: "8-10-2", title: "Concrete Acrylic Latex Painting" },
        { id: "8-10-3", title: "Concrete Masonry Painting" },
        { id: "8-10-4", title: "Concrete Staining" },
        { id: "9-9-1", title: "Wooden Walkway Installation" },
        { id: "9-9-2", title: "Wooden Walkway Sanding and Staining" },
        { id: "9-9-3", title: "Wooden Walkway Removal" },
        { id: "11-2-1", title: "Driveway Pressure Washing" },
        { id: "11-2-2", title: "Driveway Soft Washing" },
        { id: "11-2-3", title: "Driveway Deep Cleaning Solutions" },
        { id: "18-1-1", title: "Landscape Path Light Kit (6-10 lights) Installation" },
        { id: "18-1-2", title: "Solar LED In-Ground Path Light Installation" },
        { id: "18-1-3", title: "Deck Post Lighting Installation" },
        { id: "18-1-4", title: "Hardwired Path Light Installation" },
        { id: "20-5-1", title: "Organic Mulching (Up to 3” Deep)" },
        { id: "20-5-2", title: "Organic Mulching for Playgrounds" },
        { id: "20-5-3", title: "Pea Gravel Pebble Mulching" },
        { id: "20-5-4", title: "Mulch Replacement and Top-Up" },
        { id: "20-5-5", title: "Mulch Color Covering" },
        { id: "20-6-1", title: "Ground Cover Rocks Installation" },
        { id: "20-6-2", title: "Erosion Control Rocks Installation" },
        { id: "20-6-3", title: "Rock Wall Installation" },
        { id: "20-7-1", title: "Install Plastic Landscape Edging" },
        { id: "20-7-2", title: "Install Metal Landscape Edging" },
        { id: "20-7-3", title: "Install Natural Stone Landscape Edging" },
        { id: "20-7-4", title: "Install Brick Landscape Edging" },
        { id: "20-7-5", title: "Install Wood Landscape Edging" },
        { id: "20-7-6", title: "Install Paver Landscape Edging" },
        { id: "20-10-1", title: "Natural Path Installation" },
        { id: "20-10-2", title: "Concrete Walkway and Path Installation" },
        { id: "20-10-3", title: "Pavers Walkway and Path Installation" },
        { id: "20-10-4", title: "Brick Walkway and Path Installation" },
        { id: "20-10-5", title: "Stepping Stone Walkway and Path Installation" },
        { id: "20-10-6", title: "Crushed Stone or Gravel Path Installation" },
        { id: "20-10-7", title: "Surface Maintenance and Weed Control" },
        { id: "20-13-1", title: "French Drain System Installation" },
        { id: "20-13-2", title: "Downspout Runoff Installation" },
        { id: "20-13-3", title: "Landscape Drainage Solutions Installation" },
        { id: "20-13-4", title: "Driveway Drainage Solutions Installation" },
        { id: "20-13-5", title: "Yard Drainage Solutions Installation" },
        { id: "20-13-6", title: "Drainage System Cleaning" },
      ],
    },
    {
      id: "entertainment_area",
      title: "Entertainment Area",
      activities: [
        { id: "9-1-1", title: "Adjustable Helical Post Foundation Installation" },
        { id: "9-1-2", title: "Plastic Adjustable Pedestal and Framing Installation" },
        { id: "9-1-3", title: "Concrete Blocks and Lumber Foundation Installation" },
        { id: "9-1-4", title: "Pressure-Treated Wood Decking Installation" },
        { id: "9-1-5", title: "Composite Decking Installation" },
        { id: "9-1-6", title: "Deck Stairs Installation (Up to 4 Feet)" },
        { id: "9-1-7", title: "Deck Stair Balusters Installation" },
        { id: "9-1-8", title: "Deck Railing Installation" },
        { id: "9-2-3", title: "Picket Fence Installation" },
        { id: "9-3-1", title: "Cedar Pergola Kit Installation" },
        { id: "9-3-2", title: "Concrete Column Pergola Installation" },
        { id: "9-3-3", title: "Polycarbonate Roof Installation" },
        { id: "9-6-1", title: "Outdoor Storage Concrete Slab Foundation Installation" },
        { id: "9-6-2", title: "Outdoor Storage Square Patio Stone Basement Installation" },
        { id: "9-6-3", title: "Outdoor Storage Shed Installation" },
        { id: "9-6-5", title: "Storage Building Kit Installation" },
        { id: "10-5-1", title: "Wet Rated Outdoor Ceiling Fan Installation" },
        { id: "10-6-1", title: "Outdoor Home Theater Installation" },
        { id: "10-6-2", title: "Rock Speakers Installation" },
        { id: "18-1-1", title: "Landscape Path Light Kit (6-10 lights) Installation" },
        { id: "18-1-2", title: "Solar LED In-Ground Path Light Installation" },
        { id: "18-1-3", title: "Deck Post Lighting Installation" },
        { id: "18-1-4", title: "Hardwired Path Light Installation" },
        { id: "18-2-1", title: "String Light Kit Installation" },
        { id: "18-2-2", title: "Deck/Step Light Installation" },
        { id: "18-2-3", title: "Deck Post Light Installation" },
        { id: "18-3-1", title: "Single-Story Wall Light Installation" },
        { id: "22-5-1", title: "Infrared Ceiling-Mounted Electric Heater Installation" },
        { id: "22-5-2", title: "Infrared Electric Heater Replacement" },
        { id: "22-6-1", title: "Hot Tub Installation" },
        { id: "22-6-2", title: "Hot Tub Maintenance" },
        { id: "22-9-1", title: "Outdoor Mist Cooling System for Small to Midsize Patio Installation" },
        { id: "22-9-2", title: "Outdoor Mist Cooling System for Mid to Large Patio Installation" },
      ],
    },
    {
      id: "exterior_cleaning",
      title: "Exterior Cleaning",
      activities: [
        { id: "11-1-1", title: "Deck and Patio Pressure Washing" },
        { id: "11-1-2", title: "Deck and Patio Soft Washing" },
        { id: "11-1-3", title: "Deck and Patio Deep Cleaning Solutions" },
        { id: "11-2-1", title: "Driveway Pressure Washing" },
        { id: "11-2-2", title: "Driveway Soft Washing" },
        { id: "11-2-3", title: "Driveway Deep Cleaning Solutions" },
        { id: "11-3-1", title: "Hot Tub Regular Cleaning" },
        { id: "11-3-2", title: "Hot Tub Water Treatment and Cleaning" },
        { id: "11-4-1", title: "Vinyl Siding Cleaning" },
        { id: "11-4-2", title: "Wood Siding Cleaning" },
        { id: "11-4-3", title: "Brick and Stone Cleaning" },
        { id: "11-5-1", title: "Fence Pressure Washing" },
        { id: "11-5-2", title: "Fence Soft Washing" },
        { id: "11-5-3", title: "Fence Stain and Spot Removal" },
        { id: "11-6-1", title: "Gutter Debris Removal and Pressure Washing" },
        { id: "11-6-2", title: "Gutter Cleaning Using Scaffold" },
        { id: "11-7-1", title: "Roof Soft Washing" },
        { id: "11-7-2", title: "Roof, Gutter and Solar Panel Cleaning Combo" },
        { id: "11-8-1", title: "Outdoor Furniture Manual Cleaning" },
        { id: "11-8-2", title: "Exterior Lighting Fixture Cleaning" },
        { id: "11-8-3", title: "Exterior Decorative Element Cleaning" },
        { id: "11-9-1", title: "Regular Outdoor Pool Cleaning" },
        { id: "11-9-2", title: "Pool Shock Treatment" },
        { id: "11-9-3", title: "Pool Filter and Equipment Maintenance" },
        { id: "11-10-1", title: "Outdoor Glass Cleaning" },
        {
          id: "11-10-2",
          title: "Outdoor Floor-to-Ceiling Glass Cleaning on a Single Storey Building",
        },
        {
          id: "11-10-3",
          title: "Outdoor Floor-to-Ceiling Glass Cleaning on a 2-4 Storey Building",
        },
        { id: "11-10-4", title: "Outdoor High-Rise Window Cleaning" },
        { id: "11-10-5", title: "Garage Door Cleaning" },
        { id: "22-1-2", title: "Outdoor Grill Cleaning" },
        { id: "22-2-5", title: "Outdoor Kitchen Cleaning" },
        { id: "22-3-3", title: "Fire Pit Cleaning" },
        { id: "22-4-4", title: "Fireplace Cleaning" },
      ],
    },
    {
      id: "facade",
      title: "Facade",
      activities: [
        { id: "8-1-1", title: "Masonry Painting (Two Coats on a Single-Story Building)" },
        { id: "8-1-2", title: "Exterior Wood Stain Painting (Single-Story Building)" },
        { id: "8-1-3", title: "Masonry Painting (One Coat on a Single-Story Building)" },
        { id: "8-1-4", title: "Exterior Wood Painting (Two Coats on a Single-Story Building)" },
        { id: "8-1-5", title: "Wood Shingle Staining (Two Coats on a Single-Story Building)" },
        { id: "8-1-6", title: "Masonry Painting (Two Coats on a 2-3 Story Building)" },
        { id: "8-1-7", title: "Exterior Wood Stain Painting (2-3 Story Building)" },
        { id: "8-1-8", title: "Masonry Painting (One Coat on a 2-3 Story Building)" },
        { id: "8-1-9", title: "Exterior Wood Painting (Two Coats on a 2-3 Story Building)" },
        { id: "8-1-10", title: "Wood Shingle Painting (Two Coats on a 2-3 Story Building)" },
        { id: "8-1-11", title: "High-Rise Painting (Up to 60 Feet or Difficult-to-Reach Areas of the Facade)" },
        { id: "8-4-1", title: "Window Trim & Jamb Painting" },
        { id: "8-4-2", title: "Window Trim and Jamb Staining and Finishing" },
        { id: "8-4-3", title: "Window Trim Painting: One Coat" },
        { id: "8-5-1", title: "Door Slab Priming and Painting" },
        { id: "8-5-2", title: "French Door Slab Priming and Painting" },
        { id: "8-5-3", title: "Door Slab Staining and Finishing" },
        { id: "8-5-4", title: "French Door Staining and Finishing" },
        { id: "8-5-5", title: "Single Garage Door Opening and Trim Sealing and Painting" },
        { id: "8-5-6", title: "Single Garage Door Painting (One Coat)" },
        { id: "8-6-1", title: "Window Shutter Finishing" },
        { id: "8-6-2", title: "Window Shutter Painting" },
        { id: "8-6-3", title: "Window Shutter Staining and Finishing" },
        { id: "8-7-1", title: "Trim Painting with One Coat" },
        { id: "8-7-2", title: "Trim Staining and Finishing" },
        { id: "8-8-1", title: "Stucco Acrylic Latex Painting" },
        { id: "8-8-2", title: "Stucco Elastomeric Painting" },
        { id: "8-8-3", title: "Stucco Masonry Painting" },
        { id: "8-8-4", title: "Stucco Lime Washing" },
        { id: "8-9-1", title: "Brick Acrylic Latex Painting" },
        { id: "8-9-2", title: "Brick Elastomeric Painting" },
        { id: "8-9-3", title: "Brick Masonry Painting" },
        { id: "8-9-4", title: "Brick Lime Washing" },
        { id: "8-10-1", title: "Concrete Epoxy Painting" },
        { id: "8-10-2", title: "Concrete Acrylic Latex Painting" },
        { id: "8-10-3", title: "Concrete Masonry Painting" },
        { id: "8-10-4", title: "Concrete Staining" },
        { id: "18-3-1", title: "Single-Story Wall Light Installation" },
        { id: "18-3-2", title: "2-3 Story Wall Light Installation" },
        { id: "18-4-1", title: "Wall Pack Lights Installation" },
        { id: "18-4-2", title: "Area Lights Installation" },
        { id: "23-1-1", title: "Wooden Clapboard Siding Installation on a Single-Story Building" },
        { id: "23-1-2", title: "Wooden Clapboard Siding Installation on a 2-3 Story Building" },
        { id: "23-1-3", title: "Cedar Wood Shingle Siding Installation on a Single-Story Building" },
        { id: "23-1-4", title: "Cedar Wood Shingle Siding Installation on a 2-3 Story Building" },
        { id: "23-1-5", title: "Plywood Siding Panel Installation on a Single-Story Building" },
        { id: "23-1-6", title: "Plywood Siding Panel Installation on a 2-3 Story Building" },
        { id: "23-1-7", title: "Grid Siding Board Installation on a Single-Story Building" },
        { id: "23-1-8", title: "Grid Siding Board Installation on a 2-3 Story Building" },
        { id: "23-1-9", title: "Wood Siding Removal" },
        { id: "23-2-1", title: "Vinyl Siding Installation on a Single-Story Building" },
        { id: "23-2-2", title: "Vinyl Siding Installation on a 2-3 Story Building" },
        { id: "23-2-3", title: "Vinyl Siding Repair" },
        { id: "23-2-4", title: "Vinyl Siding Removal" },
        { id: "23-3-1", title: "Thin Brick Veneer Removal" },
        { id: "23-3-2", title: "Thin Brick Veneer Installation on a Single-Story Building" },
        { id: "23-3-3", title: "Thin Brick Veneer Installation on a 2-3 Story Building" },
        { id: "23-3-4", title: "Brick Veneer Sealing" },
        { id: "23-3-5", title: "Brick Veneer Pointing and Repointing" },
        { id: "23-3-6", title: "Brick Veneer Damage Repair" },
        { id: "23-4-1", title: "Old Cladding Removal" },
        { id: "23-4-2", title: "Stone Cladding Surface Preparation" },
        { id: "23-4-3", title: "Natural Stone Installation on a Single-Story Building" },
        { id: "23-4-4", title: "Natural Stone Installation on a 2-3 Story Building" },
        { id: "23-4-5", title: "Manufactured Stone Veneer Installation on a Single-Story Building" },
        { id: "23-4-6", title: "Manufactured Stone Veneer Installation on a 2-3 Story Building" },
        { id: "23-4-7", title: "Faux Stone Siding Installation on a Single-Story Building" },
        { id: "23-4-8", title: "Faux Stone Siding Installation on a 2-3 Story Building" },
        { id: "23-4-9", title: "Stone Cladding Column Wrap" },
        { id: "23-4-10", title: "Stone Cladding Protective Sealants Application" },
        { id: "23-5-1", title: "Traditional Stucco Application on a Single-Story Building" },
        { id: "23-5-2", title: "Traditional Stucco Application on a 2-3 Story Building" },
        { id: "23-5-3", title: "Old Stucco Removal on a Single-Story Building" },
        { id: "23-5-4", title: "Old Stucco Removal on a 2-3 Story Building" },
        { id: "23-6-1", title: "Galvanized Steel Panel Installation" },
        { id: "23-6-2", title: "Old Cladding Removal" },
        { id: "23-7-1", title: "Glass Blocks Installation" },
        { id: "23-7-2", title: "Glass Blocks Removal" },
        { id: "23-8-1", title: "Composite Siding Installation on a Single-Story Building" },
        { id: "23-8-2", title: "Composite Siding Installation on a 2-3 Story Building" },
        { id: "23-8-3", title: "Fiber Cement Siding Installation on a Single Story Building" },
        { id: "23-8-4", title: "Fiber Cement Siding Installation on a 2-3 Story Building" },
        { id: "23-8-5", title: "Composite Paneling Removal on a Single-Story Building" },
        { id: "23-8-6", title: "Composite Paneling Removal on a 2-3 Story Building" },
        { id: "23-9-1", title: "Fiber Cement Trim Board Installation on a Single-Story Building" },
        { id: "23-9-2", title: "Fiber Cement Trim Board Installation on a 2-3 Story Building" },
        { id: "23-9-3", title: "Trim Engineered Treated Wood Siding Installation on a Single-Story Building" },
        { id: "23-9-4", title: "Trim Engineered Treated Wood Siding Installation on a 2-3 Story Building" },
        { id: "23-9-5", title: "PVC Trim Installation on a Single-Story Building" },
        { id: "23-9-6", title: "PVC Trim Installation on a 2-3 Story Building" },
        { id: "23-9-7", title: "Custom Bent Aluminum Installation" },
        { id: "23-9-8", title: "Textured Soffit Installation" },
        { id: "23-9-9", title: "Trim and Molding Removal" },
        { id: "23-10-1", title: "House Wrap Installation" },
        { id: "23-10-2", title: "House Wrap Removal" },
        { id: "23-11-1", title: "Perimeter Bug Barrier Installation" },
        { id: "23-11-2", title: "Bird Spikes Installation" },
        { id: "23-11-3", title: "Screening Installation" },
        { id: "23-11-4", title: "Screening Replacement" },
        { id: "23-12-1", title: "Routine Façade Inspections" },
        { id: "23-12-2", title: "Façade Structural Assessment" },
        { id: "23-12-3", title: "Graffiti Removal" },
        { id: "23-12-4", title: "Concrete & Masonry Waterproofing" },
        { id: "23-12-5", title: "Exterior Wood Façade Waterproofing" },
        { id: "23-12-6", title: "Protection Façade Against Moisture" },
        { id: "24-1-1", title: "4 WiFi Security Camera System with Monitor Installation" },
        { id: "24-1-2", title: "8 WiFi Security Camera System with Monitor Installation" },
        { id: "24-1-3", title: "16 Security Camera System with Human & Vehicle Detection Installation" },
        { id: "24-2-1", title: "Battery-powered Wireless Smart Home Security Camera Installation" },
        { id: "24-2-2", title: "Small Solar Panel for Outdoor Cameras Installation" },
        { id: "24-2-3", title: "Gutter Mount Security Camera and Solar Panel Installation" },
        { id: "24-2-4", title: "Maintenance (Battery Replacement, Cleaning)" },
      ],
    },
    {
      id: "landscape",
      title: "Landscape",
      activities: [
        { id: "18-1-1", title: "Landscape Path Light Kit (6-10 lights) Installation" },
        { id: "18-1-2", title: "Solar LED In-Ground Path Light Installation" },
        { id: "18-1-3", title: "Deck Post Lighting Installation" },
        { id: "18-1-4", title: "Hardwired Path Light Installation" },
        { id: "20-2-1", title: "Lawn Hand Seeding" },
        { id: "20-2-2", title: "Lawn Hydroseeding" },
        { id: "20-2-3", title: "Lawn Sod Installation" },
        { id: "20-2-4", title: "Artificial Grass Installation" },
        { id: "20-2-5", title: "Lawn Edging Installation" },
        { id: "20-3-1", title: "Tree Removal (Under 12” Diameter, Large Canopy)" },
        { id: "20-3-2", title: "Tree Removal (12” to 24” Diameter, Large Canopy)" },
        { id: "20-3-3", title: "Tree Removal (24” to 36” Diameter, Large Canopy)" },
        { id: "20-3-4", title: "Tree Stump Grinding" },
        { id: "20-3-5", title: "Tree Formative Pruning" },
        { id: "20-4-1", title: "Small Tree Planting (Up to 2’ Tall)" },
        { id: "20-4-2", title: "Medium Tree Planting (3’ to 5’ Tall)" },
        { id: "20-4-3", title: "Large Tree Planting (Over 6’ Tall)" },
        { id: "20-4-4", title: "Medium Size Tree Relocation" },
        { id: "20-4-5", title: "Shrubs Planting" },
        { id: "20-4-6", title: "Perennial Grasses Planting" },
        { id: "20-5-1", title: "Organic Mulching (Up to 3” Deep)" },
        { id: "20-5-2", title: "Organic Mulching for Playgrounds" },
        { id: "20-5-3", title: "Pea Gravel Pebble Mulching" },
        { id: "20-5-4", title: "Mulch Replacement and Top-Up" },
        { id: "20-5-5", title: "Mulch Color Covering" },
        { id: "20-6-1", title: "Ground Cover Rocks Installation" },
        { id: "20-6-2", title: "Erosion Control Rocks Installation" },
        { id: "20-6-3", title: "Rock Wall Installation" },
        { id: "20-7-1", title: "Install Plastic Landscape Edging" },
        { id: "20-7-2", title: "Install Metal Landscape Edging" },
        { id: "20-7-3", title: "Install Natural Stone Landscape Edging" },
        { id: "20-7-4", title: "Install Brick Landscape Edging" },
        { id: "20-7-5", title: "Install Wood Landscape Edging" },
        { id: "20-7-6", title: "Install Paver Landscape Edging" },
        { id: "20-8-1", title: "Raised Garden Bed Installation (Wood)" },
        { id: "20-8-2", title: "Raised Garden Bed Installation (Corten Steel)" },
        { id: "20-8-3", title: "Raised Garden Bed Installation (Galvanized Steel)" },
        { id: "20-9-1", title: "Hedge Planting" },
        { id: "20-9-2", title: "Hedge Pruning" },
        { id: "20-10-1", title: "Natural Path Installation" },
        { id: "20-10-2", title: "Concrete Walkway and Path Installation" },
        { id: "20-10-3", title: "Pavers Walkway and Path Installation" },
        { id: "20-10-4", title: "Brick Walkway and Path Installation" },
        { id: "20-10-5", title: "Stepping Stone Walkway and Path Installation" },
        { id: "20-10-6", title: "Crushed Stone or Gravel Path Installation" },
        { id: "20-10-7", title: "Surface Maintenance and Weed Control" },
        { id: "20-11-1", title: "Small Landscape Fountain Installation" },
        { id: "20-11-2", title: "Preformed Pond Installation" },
        { id: "20-11-3", title: "Ponds and Fountains Maintenance" },
        { id: "20-12-1", title: "Sprinkler Systems Installation" },
        { id: "20-12-2", title: "Irrigation Timers and Controllers Installation" },
        { id: "20-12-3", title: "Drip Irrigation System Installation" },
        { id: "20-12-4", title: "Raised Bed Garden Drip Irrigation System Installation" },
        { id: "20-12-5", title: "Irrigation System Winterization" },
        { id: "20-12-6", title: "Irrigation System Maintenance" },
        { id: "20-13-1", title: "French Drain System Installation" },
        { id: "20-13-2", title: "Downspout Runoff Installation" },
        { id: "20-13-3", title: "Landscape Drainage Solutions Installation" },
        { id: "20-13-4", title: "Driveway Drainage Solutions Installation" },
        { id: "20-13-5", title: "Yard Drainage Solutions Installation" },
        { id: "20-13-6", title: "Drainage System Cleaning" },
        { id: "20-14-1", title: "Aluminum Frame Greenhouse Installation" },
        { id: "20-14-2", title: "Metal Orangerie Installation" },
        { id: "20-14-3", title: "Greenhouse Seasonal Cleaning" }
      ]
    },
    {
      id: "outdoor_kitchen",
      title: "Outdoor Kitchen",
      activities: [
        { id: "9-4-1", title: "Cedar Gazebo Kit Installation" },
        { id: "9-4-2", title: "Concrete Column Gazebo Installation" },
        { id: "9-4-3", title: "Gazebo Roof Installation" },
        { id: "9-4-4", title: "Gazebo Removal" },
        { id: "9-5-1", title: "Outdoor Furniture Assembly" },
        { id: "9-6-1", title: "Outdoor Storage Concrete Slab Foundation Installation" },
        { id: "9-6-2", title: "Outdoor Storage Square Patio Stone Basement Installation" },
        { id: "9-6-3", title: "Outdoor Storage Shed Installation" },
        { id: "9-6-4", title: "Carport Installation" },
        { id: "9-6-5", title: "Storage Building Kit Installation" },
        { id: "9-6-6", title: "Patio Cover Installation" },
        { id: "9-6-7", title: "Outdoor Storage Removal" },
        { id: "10-2-1", title: "Backyard Outlet Installation" },
        { id: "10-2-2", title: "Weatherproof Outlet Installation" },
        { id: "10-2-3", title: "Backyard Outlet with Switch Installation" },
        { id: "22-1-1", title: "Outdoor Grill Assembly" },
        { id: "22-1-2", title: "Outdoor Grill Cleaning" },
        { id: "22-2-1", title: "Outdoor Kitchen Cabinets Installation" },
        { id: "22-2-2", title: "Outdoor Kitchen Built-In Grill Installation" },
        { id: "22-2-3", title: "Outdoor Kitchen Built-In Grill Installation" },
        { id: "22-2-4", title: "Outdoor Kitchen Sink Installation" },
        { id: "22-2-5", title: "Outdoor Kitchen Cleaning" },
        { id: "22-2-6", title: "Outdoor Kitchen Removal" },
        { id: "22-8-1", title: "Built-In Outdoor Cooler Installation" },
        { id: "22-8-2", title: "Outdoor Refrigeration Electrical Repair" },
        { id: "22-8-3", title: "Outdoor Refrigeration System Maintenance" }
      ]
    },
    {
      id: "patio",
      title: "Patio",
      activities: [
        { id: "8-3-1", title: "Deck Staining and Finishing" },
        { id: "8-3-2", title: "Deck Coating (Acrylic Polymer)" },
        { id: "8-3-3", title: "Deck Painting (One Coat)" },
        { id: "8-3-4", title: "Deck Priming and Painting" },
        { id: "8-4-1", title: "Window Trim & Jamb Painting" },
        { id: "9-1-1", title: "Adjustable Helical Post Foundation Installation" },
        { id: "9-1-2", title: "Plastic Adjustable Pedestal and Framing Installation" },
        { id: "9-1-3", title: "Concrete Blocks and Lumber Foundation Installation" },
        { id: "9-1-4", title: "Pressure-Treated Wood Decking Installation" },
        { id: "9-1-5", title: "Composite Decking Installation" },
        { id: "9-1-6", title: "Deck Stairs Installation (Up to 4 Feet)" },
        { id: "9-1-7", title: "Deck Stair Balusters Installation" },
        { id: "9-1-8", title: "Deck Railing Installation" },
        { id: "9-1-9", title: "Glass Railing Installation" },
        { id: "9-1-10", title: "Glass Deck Gate Installation" },
        { id: "9-1-11", title: "Aluminum Deck Gate Installation" },
        { id: "9-1-12", title: "Non-Slip Aluminum Nosing Installation" },
        { id: "9-1-13", title: "Deck Plank Removal" },
        { id: "9-1-14", title: "Deck Sanding, Staining, and Finishing" },
        { id: "9-8-1", title: "4-Step Outdoor Stair Installation" },
        { id: "9-8-2", title: "5-Step Outdoor Stair Installation" },
        { id: "9-8-3", title: "6-Step Outdoor Stair Installation" },
        { id: "9-8-4", title: "8-Step Outdoor Stair Installation" },
        { id: "9-8-5", title: "6-Foot Staircase Landing Installation" },
        { id: "9-8-6", title: "8-Foot Staircase Landing Installation" },
        { id: "9-8-7", title: "Outdoor Staircase Concrete Foundation Pillar and Columns Installation" },
        { id: "9-8-8", title: "Outdoor Staircase Adjustable Ground Spike Foundation Installation" },
        { id: "9-8-9", title: "Outdoor Staircase Step Replacement" },
        { id: "9-8-10", title: "Outdoor Staircase Hand Rail Replacement" },
        { id: "9-8-11", title: "Outdoor Staircase Removal (Per Rise)" },
        { id: "10-2-1", title: "Backyard Outlet Installation" },
        { id: "10-2-2", title: "Weatherproof Outlet Installation" },
        { id: "10-2-3", title: "Backyard Outlet with Switch Installation" },
        { id: "10-5-1", title: "Wet Rated Outdoor Ceiling Fan Installation" },
        { id: "18-2-1", title: "String Light Kit Installation" },
        { id: "18-2-2", title: "Deck/Step Light Installation" },
        { id: "18-2-3", title: "Deck Post Light Installation" },
        { id: "18-3-1", title: "Single-Story Wall Light Installation" },
        { id: "22-1-1", title: "Outdoor Grill Assembly" },
        { id: "22-1-2", title: "Outdoor Grill Cleaning" },
        { id: "22-2-1", title: "Outdoor Kitchen Cabinets Installation" },
        { id: "22-2-2", title: "Outdoor Kitchen Built-In Grill Installation" },
        { id: "22-2-3", title: "Outdoor Kitchen Built-In Grill Installation" },
        { id: "22-2-4", title: "Outdoor Kitchen Sink Installation" },
        { id: "22-2-5", title: "Outdoor Kitchen Cleaning" },
        { id: "22-2-6", title: "Outdoor Kitchen Removal" },
        { id: "22-4-1", title: "Compact Outdoor Fireplace Installation" },
        { id: "22-4-2", title: "Compact Wood Box Installation" },
        { id: "22-4-3", title: "Compact Outdoor Hearth Installation" },
        { id: "22-4-4", title: "Fireplace Cleaning" },
        { id: "22-4-5", title: "Fireplace Removal" },
        { id: "22-5-1", title: "Infrared Ceiling-Mounted Electric Heater Installation" },
        { id: "22-5-2", title: "Infrared Electric Heater Replacement" },
        { id: "22-8-1", title: "Built-In Outdoor Cooler Installation" },
        { id: "22-9-1", title: "Outdoor Mist Cooling System for Small to Midsize Patio Installation" },
        { id: "22-9-2", title: "Outdoor Mist Cooling System for Mid to Large Patio Installation" },
        { id: "24-2-1", title: "Battery-powered Wireless Smart Home Security Camera Installation" },
        { id: "24-2-2", title: "Small Solar Panel for Outdoor Cameras Installation" },
        { id: "24-2-3", title: "Gutter Mount Security Camera and Solar Panel Installation" }
      ]
    },
    {
      id: "playground",
      title: "Playground",
      activities: [
        { id: "9-7-1", title: "Swing Sets Installation" },
        { id: "9-7-2", title: "Playhouse Installation" },
        { id: "9-7-3", title: "Sandbox Installation" },
        { id: "20-5-2", title: "Organic Mulching for Playgrounds" },
        { id: "20-7-1", title: "Install Plastic Landscape Edging" },
        { id: "20-7-3", title: "Install Natural Stone Landscape Edging" },
        { id: "20-9-1", title: "Hedge Planting" },
        { id: "20-9-2", title: "Hedge Pruning" },
        { id: "20-10-6", title: "Crushed Stone or Gravel Path Installation" }
      ]
    }
  ],
};
