/**
 * scripts/generate-embeddings.ts
 *
 * This script:
 * 1) Loads the list of all 1000+ service titles.
 * 2) For each service title, calls OpenAI's embedding API (text-embedding-3-small).
 * 3) Stores the resulting embedding vector into a JSON file, "services-with-embeddings.json".
 *
 * Usage:
 *   OPENAI_API_KEY=sk-xxxx npx ts-node scripts/generate-embeddings.ts
 * or define OPENAI_API_KEY in your .env and run a custom npm script.
 */

import fs from "fs";
import path from "path";
import OpenAI from "openai";

// Make sure you have OPENAI_API_KEY in your environment
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

/**
 * Here is your full list of ~1000 services (titles) as a string array.
 * Below is the entire list from your question, each line as an element in the array.
 */
const allServices = [
  "Battery-Operated Smoke Detector Installation",
  "Hardwired Smoke Detector Installation",
  "Smoke Detector Detach and Reset",
  "Ceiling Fan Replacement",
  "Ceiling Fan Removal",
  "Light Fixture Removal",
  "Light Fixture Installation",
  "Wall Sconce Installation",
  "Recessed Light Installation",
  "Switch Replacement",
  "1-Gang Switch Installation",
  "2-Gang Switch Installation",
  "3-Gang Switch Installation",
  "1-Gang Toggle Switch Installation",
  "2-Gang Toggle Switch Installation",
  "3-Gang Toggle Switch Installation",
  "Humidity Sensor Installation",
  "Motion Sensor Installation",
  "15 Amp Outlet Installation",
  "30 Amp Outlet Installation",
  "50 Amp Outlet Installation",
  "Phone, TV, or Speaker Outlet Installation",
  "Floor Outlet Installation",
  "Dimmer Switch Installation",
  "Wi-Fi Dimmer Installation (Google, Alexa, HomeKit)",
  "Wi-Fi Motion Sensor Dimmer Installation",
  "Countdown Timer Installation",
  "Chandelier Installation",
  "Crystal Chandelier Installation",
  "Chandelier Detach and Reset (up to 6 lights)",
  "Chandelier Detach and Reset (more than 6 lights)",
  "Wiring with PVC Conduit Installation",
  "Wiring Installation (no conduits)",
  "Wiring with Metal Conduit Installation",
  "Circuit Breaker and Fuse Troubleshooting",
  "Faulty Wiring and Connection Troubleshooting",
  "Lighting and Fixture Troubleshooting",
  "Outlet and Switch Malfunction Troubleshooting",
  "Track Lighting Kit Installation",
  "Fixed Track Lighting Installation",
  "Toilet Supply and Installation",
  "Flange and Wax Ring Replacement",
  "Tank Flapper Replacement",
  "Flush Mechanism Repair",
  "Manual Diaphragm Flush Valve Replacement",
  "Urinal Installation",
  "Smart Toilet Bidet Installation",
  "Electric Bidet Seat Installation",
  "Faucet Replacement",
  "Rectangular Tub/Shower Combo Installation",
  "Shower Base Replacement",
  "Shower Walls Replacement",
  "Sliding Shower Door Installation",
  "Freestanding Bathtub and Faucet Installation",
  "Alcove Bathtub Installation",
  "Tub Surrounds Installation",
  "Sliding Bathtub Door Installation",
  "Vessel Sink Installation",
  "Undermount Sink Installation",
  "Pedestal Sink Installation",
  "Wall Mount Sink Installation",
  "Old Sink Removal",
  "Undermount Kitchen Sink Installation",
  "Double Basin Sink Installation",
  "Vessel Sink Faucet Installation",
  "Undermount Sink Faucet Installation",
  "Pedestal Sink Faucet Installation",
  "Single Hole Faucet Installation",
  "Kitchen Faucet Installation",
  "Wall Mounted Potfiller Installation",
  "Bidet Sprayer Installation",
  "Gas Water Heater Installation",
  "Electric Water Heater Installation",
  "Old Water Heater Removal",
  "Electric Tankless Water Heater Installation",
  "Garbage Disposal Installation",
  "Garbage Disposal Removal",
  "Drain Line Camera Inspection",
  "Clog Clearing",
  "PEX Rough-In Plumbing per Fixture",
  "Floor/Laundry Pan Drain Rough-In Plumbing",
  "3/4” Pipe Emergency Repair",
  "1/2” Pipe Emergency Repair",
  "White Wall Painting (Two Coats)",
  "Wall Painting Refresh (One Coat)",
  "Color Wall Painting (Two Coats)",
  "Bathroom Wall Painting (White)",
  "Bathroom Wall Painting (Color)",
  "Concrete and Masonry Wall Painting",
  "Wall Staining and Finishing",
  "Ceiling Painting: Seal, Prime, and Paint",
  "One Coat Refresh Ceiling Painting",
  "Popcorn Ceiling Removal",
  "Popcorn Ceiling Installation",
  "White Trim and Molding Painting (One Coat Refresh)",
  "Color Trim and Molding Painting (Two Coats)",
  "Trim and Molding Staining and Finishing",
  "White Door Painting (One Side)",
  "White Door Painting (Two Sides, Jamb, and Trim)",
  "Color Door Painting (One Side)",
  "Color Door Painting (Two Sides, Jamb, and Trim)",
  "Door Staining and Finishing (One Side, Jamb, and Trim)",
  "Door Staining and Finishing (Two Sides, Jamb, and Trim)",
  "White Window Painting (One Side)",
  "White Window Painting (Two Sides, Jamb, and Trim)",
  "Color Window Painting (One Side)",
  "Color Window Painting (Two Sides, Jamb, and Trim)",
  "Window Staining and Finishing (One Side, Jamb, and Trim)",
  "Window Staining and Finishing (Two Sides, Jamb, and Trim)",
  "Full Height Cabinet Strip and Refinish (Faces Only)",
  "Lower/Upper Cabinet Strip and Refinish (Faces Only)",
  "Full Height Cabinet Seal and Paint",
  "Lower/Upper Cabinet Seal and Paint",
  "Full-height Cabinet Painting",
  "Lower/Upper Cabinet Painting",
  "Wallpaper Removal",
  "Wallpaper Installation",
  "Fabric Wallpaper Installation",
  "Sisal Wallpaper Installation",
  "Border Installation",
  "Paintable Wallpaper Installation",
  "Concrete and Masonry Painting (Two Coats)",
  "Block Sealing",
  "Mold Removal and Wall Protection",
  "Baseboard Painting",
  "Baseboard Staining and Finishing",
  "Ceramic Tile Removal",
  "Ceramic Tile Installation",
  "Ceramic Tile Repair",
  "Ceramic Tile Customization",
  "Ceramic Tile Regrouting",
  "Porcelain Tile Removal",
  "Porcelain Tile Installation",
  "Porcelain Tile Repair",
  "Porcelain Tile Customization",
  "Porcelain Tile Regrouting",
  "Natural Stone Removal",
  "Wall veneer panels Installation",
  "Natural Stone Tile Installation",
  "Natural Stone Sill Installation",
  "Natural Stone Threshold Installation",
  "Natural Stone Countertop Installation",
  "Cut for sink opening in natural marble ",
  "Natural Stone Mosaic Installation",
  "Marble Mosaic Installation",
  "Glass Mosaic Installation",
  "Porcelain Mosaic Installation",
  "Mosaic removal",
  "Bathroom Demolition and Removal",
  "Waterproofing and Tile Shower Installation (up to 60 SF)",
  "Waterproofing and Tile Shower Installation (61 to 100 SF)",
  "Waterproofing and Tile Shower Installation (101 to 120 SF)",
  "Waterproofing and Tile Shower Installation (101 to 120 SF)",
  "Bathroom Mirror Installation",
  "Bathroom Accessories Installation",
  "Countertop Tile Installation",
  "Tile Backsplash Installation",
  "Natural Stone Countertop Installation",
  "Solid Surface Countertop Installation",
  "Floor Tile Installation",
  "Tile Floor Regrouting",
  "Tile and Stone Repair",
  "Fireplace Hearth Tile Installation",
  "Masonry Fireplace & Chimney Removal",
  "Chimney Veneer Installation",
  "Chimney Veneer Removal",
  "Veneer and Chimney Cleaning ",
  "Leveling with Cement",
  "Mortar Bed Preparation for Tile Floors",
  "Mortar Bed Removal",
  "Mortar Bed Preparation for Tile Walls",
  "Uncoupling Mat for Tile Installation",
  "Cement board Installation",
  "Vanity Top Removal",
  "Single Sink Installation",
  "Double Sink Installation",
  "Floor Heating Mat Installation",
  "Ditra-Heat Heating Cables Installation",
  "Carpet Removal",
  "Carpet Installation",
  "Carpet Tile Installation",
  "Stairs Carpet Installation",
  "Carpet Pad Removal",
  "Carpet Pad Installation",
  "Vinyl Tile Removal",
  "Vinyl tile Installation",
  "Self-Adhesive Vinyl Tile Installation",
  "Vinyl Covering Removal",
  "Vinyl Covering Installation",
  "Vinyl Plank Installation",
  "Vinyl Stair Tread Installation",
  "Laminate Flooring Removal",
  "Laminate Flooring Installation",
  "Bamboo Flooring Removal",
  "Bamboo flooring Installation",
  "Wood Floor Sanding, Staining, and Finishing",
  "Parquet Flooring Removal",
  "Pre-Finished Solid Wood Flooring Removal",
  "Pre-finished Solid Wood Installation",
  "Pre-Finished Solid Wood Floor Repair",
  "Engineered Wood Removal",
  "Engineered Wood Floating Floor Installation",
  "Engineered Wood Glue-Down Floor Installation",
  "Plywood Underlayment Removal",
  "Plywood Underlayment Installation",
  "Baseboard Removal",
  "Baseboard Installation",
  "Full Height Cabinet Detachment and Resetting",
  "Full Height Cabinet Removal",
  "Upper (Wall) or Lower (Base) Cabinet Installation",
  "Cabinet Drawer Front Installation",
  "Cabinetry Restoration and Repair",
  "Baseboard Installation",
  "Casing Installation",
  "Brick Mold Installation",
  "Crown Molding Installation",
  "6-Inch Load-Bearing Wall Installation",
  "4-Inch Non-Bearing Wall Installation",
  "Curved Wall (Radius) Installation",
  "Ceiling Structure Installation",
  "Rafter Structure Installation",
  "Framing Removal from Structure",
  "Column Installation",
  "Engineered Strand Lumber Installation",
  "Beam Installation",
  "Building Foundation Excavation",
  "Foundation Backfilling",
  "Concrete Wall Installation",
  "Concrete Column Installation",
  "12-Inch Concrete Pile Installation",
  "Concrete Patching (up to 14 sq. ft.)",
  "Concrete Step Installation",
  "6-Inch Suspended Concrete Slab Installation",
  "Helical Post Installation",
  "Interior Door Removal",
  "Interior Door Installation",
  "Exterior Door Installation",
  "Patio Door Installation",
  "Barn Door Installation",
  "Pocket Door Installation",
  "Sliding Closet Door Installation",
  "8-9 Foot Garage Door Installation",
  "16 Foot Garage Door Installation",
  "Garage Door Repair",
  "Cat Door Installation",
  "Dog Door Installation",
  "Pet and Dog Patio Door Installation",
  "Window Reglazing (up to 24x36 inches)",
  "Aluminum Window Installation (up to 40 square feet)",
  "Vinyl Window Installation (up to 40 square feet)",
  "Wood Window Installation (up to 40 square feet)",
  "Glass Block Window Installation",
  "Window Removal",
  "Skylight Installation",
  "Raised Panel Shutters Installation",
  "Unfinished Stringers, Treads & Risers Installation",
  "Prefinished Treads & Steel Stringers Installation",
  "Staircase Removal",
  "Stair Treads and Risers Replacement",
  "Spiral Staircase Installation",
  "Handrail Installation",
  "Overlapping Wainscot Installation",
  "Beadboard Panel Installation",
  "Shiplap Board Installation",
  "Decorative Panels Installation",
  "Wood Panel Removal",
  "Butcher Block Countertop Installation",
  "Butcher Block Countertop Restoration",
  "Natural Stone Countertop Restoration",
  "Laminate Countertop Installation",
  "Countertop Subdeck Installation",
  "Countertop Removal",
  "Furnace Removal",
  "Furnace Installation",
  "Furnace Cleaning, Servicing, and Filter Replacement",
  "Furnace Ignitor Replacement",
  "Heat Exchanger Replacement",
  "Burner Replacement",
  "Control Board Replacement",
  "Routine Furnace Maintenance",
  "Boiler Removal",
  "Gas Boiler Installation",
  "Electric Boiler Installation",
  "Boiler Regular Maintenance",
  "Heat Pump Removal",
  "Heat Pump Installation",
  "Heat Pump Diagnostic and Troubleshooting",
  "Heat Pump Regular Maintenance",
  "Heat Pump Refrigerant Recharge and Leak Repair",
  "Heat Pump Component Replacement and Repair",
  "Mini Split Air Conditioner Removal",
  "Mini Split Air Conditioner Installation",
  "2 Zone Mini Split Air Conditioner Installation",
  "3 Zone Mini Split Air Conditioner Installation",
  "Mini Split Air Conditioner Diagnostics and Troubleshooting",
  "Mini Split Air Conditioner Routine Maintenance",
  "Mini Split Air Conditioner Refrigerant Management",
  "Window AC Removal",
  "Window AC Installation",
  "Window AC Routine Maintenance",
  "Window AC Diagnostic and Troubleshooting",
  "Bathroom Ventilation Fan Removal",
  "Bathroom Ventilation Fan Installation",
  "Bathroom Ventilation Fan Replacement",
  "Ventilation System Duct Cleaning and Maintenance",
  "Ventilation System Motor and Belt Replacement",
  "Ventilation System Balancing",
  "Ventilation System Vibration and Noise Reduction",
  "Hot or Cold Air System Installation",
  "Ductwork Removal",
  "Thermostat Replacement",
  "Smart Thermostat Installation",
  "Baseboard Electric Heater Installation",
  "Baseboard Hydronic Heater Installation",
  "Electric Wall Heater Installation",
  "Garage Air Heater Installation",
  "Dehumidifier Installation",
  "Humidifier Installation",
  "Air Purifier Installation",
  "Humidifier/Dehumidifier Maintenance",
  "Electric Stove Installation",
  "Gas Stove Installation",
  "Wood Burning Stove Installation",
  "Pellet Stove Installation",
  "Chimney Sweeping for Stoves",
  "Electric Fireplace Installation",
  "Gas Fireplace (Ventless) Installation",
  "Fireplace Removal",
  "1BED/1BATH Regular Cleaning",
  "2BED/1BATH Regular Cleaning",
  "2BED/2BATH Regular Cleaning",
  "3BED/2BATH Regular Cleaning",
  "3BED/3BATH Regular Cleaning",
  "4BED/3BATH Regular Cleaning",
  "4BED/4BATH Regular Cleaning",
  "4BED/5BATH Regular Cleaning",
  "5BED/5BATH Regular Cleaning",
  "1BED/1BATH General Cleaning",
  "2BED/1BATH General Cleaning",
  "2BED/2BATH General Cleaning",
  "3BED/2BATH General Cleaning",
  "3BED/3BATH General Cleaning",
  "4BED/3BATH General Cleaning",
  "4BED/4BATH General Cleaning",
  "4BED/5BATH General Cleaning",
  "5BED/5BATH General Cleaning",
  "Fireplace Chimney Sweep Cleaning and Service",
  "Heavy Stain Carpet Cleaning and Deodorizing",
  "Carpet Stairs Cleaning",
  "Tile - Heavy Cleaning",
  "Natural Marble - Heavy Cleaning",
  "Window Cleaning (per side) 41 - 60 SF ",
  "Window Cleaning (Per Side) 41 - 60 SF",
  "Window Screen Cleaning ",
  "Office Cleaning",
  "Retail Store Cleaning",
  "Post Corporate Event Cleaning",
  "Post-Wedding Cleaning",
  "Final Cleaning after Construction",
  "Flood Damage Cleanup",
  "Fire and Smoke Damage Cleanup",
  "Chemical Spill Cleanup",
  "Crime Scene Cleanup",
  "Drywall Repair (Up to 4 Square Feet)",
  "Drywall Repair (Holes & Cracks Up to 3 Inches)",
  "Corner Bead Repair",
  "Drywall Cracks Repair",
  "Machine Texturing for Drywall",
  "Heavy Hand Texturing for Drywall",
  "Skim Coat for Drywall",
  "Acoustic Drywall Installation",
  "Drop Ceiling Tiles Installation (Acoustic Improvement)",
  "Drop Ceiling Tiles Repair and Painting",
  "Acoustical/Fire-Safing 4-Inch Insulation",
  "Double-Sided Drywall Installation with Metal Studs (Up to 10 Feet Height)",
  "Drywall Installation (Hung, Taped, Floated, Ready for Paint)",
  "Venetian Plaster Application – Two Coats",
  "Venetian Plaster Application – Three Coats",
  "Venetian Plaster Application – Four Coats",
  "Curved Ceiling Installation",
  "Drywall Ceiling Installation (Ready to Paint)",
  "Water-resistant Drywall Ceiling Installation",
  "Drywall Bulkhead Installation",
  "Smooth Drywall Finishing",
  "Orange Peel Texture Finishing",
  "Skim Coat Drywall Finishing",
  "Level 5 Drywall Finishing",
  "Fire-Rated Drywall Installation",
  "Fiberglass-Faced Drywall Installation",
  "Impact-Resistant Drywall Installation",
  "Full Scale Drywall Removal",
  "Selective Drywall Demolition",
  "Debris Management and Disposal",
  "Historical Preservation and Renovation",
  "Preparation for Reinstallation",
  "Structural Brick Removal",
  "Concrete Block Installation",
  "Brick Veneer Installation",
  "Brick Veneer Sandblasting",
  "Refrigerator Removal",
  "Top or Bottom Freezer Installation",
  "Side by Side Installation",
  "Custom Refrigerator Installation",
  "Wine Cooler Installation",
  "Refrigerator Not Cooling",
  "Refrigerator Overcooling",
  "Water Leakage Inside or Outside ",
  "Buildup of Frost in the Freezer",
  "Ice Maker Not Working",
  "Fridge Making Strange Noises",
  "Malfunctioning Water Dispenser",
  "Refrigerator Light Not Working",
  "Refrigerator Door Not Sealing Properly",
  "Temperature Inconsistencies in Fridge or Freezer Section",
  "Compressor Issues",
  "Refrigerant Leak",
  "Control Board Defect",
  "Non-Operating Fans",
  "Oven Removal",
  "Freestanding Gas Range Installation",
  "Freestanding Electric Range Installation",
  "Gas Cooktop Installation",
  "Electric Cooktop Installation",
  "Wall Oven Installation",
  "Oven Electrical Repair",
  "Oven Mechanical Repair",
  "Oven Gas Repair",
  "Oven Calibration and Maintenance",
  "Dishwasher Removal",
  "Dishwasher Installation",
  "Dishwasher Water Flow and Drainage Repair",
  "Dishwasher Electrical and Control Repair",
  "Dishwasher Heating and Drying Repair",
  "Dishwasher Mechanical and Interior Repair",
  "Washer Removal",
  "Smart Washer Installation",
  "Laundry Center Installation",
  "Washer Water-Related Repair",
  "Washer Mechanical Repair",
  "Washer Electrical and Control Repair",
  "Washer Vibration and Noise Repair",
  "Dryer Removal",
  "Electric Dryer Installation",
  "Gas Dryer Installation",
  "Dryer Vent Cleaning",
  "Dryer Thermal and Airflow Repair",
  "Dryer Mechanical Repair",
  "Dryer Electrical Repair",
  "Dryer Noise and Vibration Repair",
  "Microwave Removal",
  "Built-In Microwave Installation",
  "Over-the-Range Microwave Installation",
  "Microwave Electrical and Electronic Repair",
  "Microwave Mechanical Repair ",
  "Range Hood Removal",
  "Wall Mount Range Hood Installation",
  "Under Cabinet Range Hood Installation",
  "Range Hood Cleaning and Maintenance",
  "Appliance Electrical Tests",
  "Appliance Mechanical Tests",
  "Appliance Error Code Analysis",
  "Performance Tests",
  "Appliance Gas System Diagnostic",
  "Appliance Water System Diagnostic",
  "Appliance Thermal Diagnostic",
  "Appliance Noise and Vibration Diagnostic",
  "Appliance Connectivity Diagnostic",
  "Appliance Energy Efficiency Diagnostic",
  "Fire Alarm Detector Installation",
  "Carbon Monoxide Detector Installation",
  "Wired Security Camera System Installation",
  "Wireless Indoor/Outdoor Security Camera Installation",
  "Floodlight Wired Camera Installation",
  "Smart WiFi Lock Installation",
  "Smart Lock Maintenance and Troubleshooting",
  "Wireless Video Doorbell Installation",
  "Wired Doorbell Installation",
  "Wireless Security System Kit Installation",
  "Pedestrian Gate Lock Installation",
  "Motion Sensor for Light Fixture Installation",
  "Outdoor Motion Sensor Installation",
  "Home Security Door/Window Installation",
  "Garage Door Safety Sensors Installation",
  "Smart Leak Detectors Installation",
  "Smart Water Detector and Automatic Water Shutoff Installation",
  "Built-in Theater Projector Installation",
  "Built-in Theater Projector Repair",
  "Projection Screen Installation",
  "Theater Sound System Installation",
  "In-wall / In-ceiling Speaker Installation",
  "Public Address Speaker Installation",
  "Home Stereo Receiver Installation",
  "Rough-in for Audio/Visual (Per Room)",
  "TV Panel Installation (Up to 64”)",
  "TV Panel Installation (Up to 90”)",
  "Wireless Router Installation",
  "Wi-Fi Range Extender Installation",
  "Wi-Fi Troubleshooting",
  "Studiofoam Wedges Installation",
  "Paintable Sound Absorbing Acoustic Panels Installation",
  "Home Theater Troubleshooting",
  "Flat-Pack Furniture Assembly (Small and Medium Items)",
  "Flat-Pack Furniture Assembly (Large Items)",
  "Office Furniture Assembly",
  "Outdoor Furniture Assembly",
  "Children’s Simple Furniture Assembly",
  "Children’s Playsets Assembly",
  "Entertainment Centers and TV Stand Assembly",
  "Exercise Equipment Assembly",
  "Bedroom Furniture Assembly",
  "Shelf Mounting",
  "Small and Medium Picture Hanging Installation",
  "Large Picture Hanging Installation",
  "Frameless Mirror Hanging Installation",
  "Framed Mirror Hanging",
  "Minor Surface and Structural Repair",
  "Cabinet Mechanism Repairs",
  "Structural Repairs",
  "Hardware Replacement",
  "Wood Furniture Cleaning",
  "Stainless Steel Furniture Cleaning",
  "Copper and Brass Furniture Cleaning",
  "Metal and Cast Iron Furniture Cleaning",
  "Garage Storage Installation",
  "Closet Organizer Installation",
  "Wire Closet Organizer Installation",
  "Shelving Installation",
  "Leather Upholstery Cleaning",
  "Fabric Upholstery Cleaning",
  "Upholstery Repair",
  "Large Furniture Removal",
  "Cabinet Removal",
  "Estate Cleanout",
  "Reception Desk Installation",
  "Executive Desk Installation",
  "Computer Desks Installation",
  "Room Divider Installation",
  "Entire Apartment Move",
  "Kitchen Move",
  "Living Room Move",
  "Master Bedroom Move ",
  "Bathroom Move",
  "Garage Move",
  "Office Move",
  "Clothing Store Move",
  "Coffee Shop/Restaurant Move",
  "Entire Apartment Packing and Unpacking",
  "Kitchen Packing and Unpacking",
  "Living Room Packing and Unpacking",
  "Bedroom Packing and Unpacking",
  "Bathroom Packing and Unpacking",
  "Garage Packing and Unpacking",
  "Office Packing and Unpacking",
  "Store Packing and Unpacking",
  "Coffee Shop/Restaurant Packing and Unpacking",
  "Piano Move",
  "Art and Antiques Move",
  "Chandelier Move",
  "Vehicle Transport Move",
  "Miscellaneous Indoor Storage",
  "1-2 Bedroom Home Indoor Storage",
  "2-3 Bedroom Home Indoor Storage",
  "4 Bedroom Home or Larger Indoor Storage",
  "Office or Warehouse Indoor Storage",
  "Pre-Move Cleaning",
  "Post-Move Cleaning",
  "Masonry Painting (Two Coats on a Single-Story Building)",
  "Exterior Wood Stain Painting (Single-Story Building)",
  "Masonry Painting (One Coat on a Single-Story Building)",
  "Exterior Wood Painting (Two Coats on a Single-Story Building)",
  "Wood Shingle Staining (Two Coats on a Single-Story Building)",
  "Masonry Painting (Two Coats on a 2-3 Story Building)",
  "Exterior Wood Stain Painting (2-3 Story Building)",
  "Masonry Painting (One Coat on a 2-3 Story Building)",
  "Exterior Wood Painting (Two Coats on a 2-3 Story Building)",
  "Wood Shingle Painting (Two Coats on a 2-3 Story Building)",
  "High-Rise Painting (Up to 60 Feet or Difficult-to-Reach Areas of the Facade)",
  "Ornamental Fence Priming and Painting",
  "Wood Fence or Gate Staining",
  "Wood Fence or Gate Sealing and Painting",
  "Wood Fence Post Painting and Finishing",
  "Deck Staining and Finishing",
  "Deck Coating (Acrylic Polymer)",
  "Deck Painting (One Coat)",
  "Deck Priming and Painting",
  "Window Trim & Jamb Painting",
  "Window Trim and Jamb Staining and Finishing",
  "Window Trim Painting: One Coat",
  "Door Slab Priming and Painting",
  "French Door Slab Priming and Painting",
  "Door Slab Staining and Finishing",
  "French Door Staining and Finishing",
  "Single Garage Door Opening and Trim Sealing and Painting",
  "Single Garage Door Painting (One Coat)",
  "Window Shutter Finishing",
  "Window Shutter Painting ",
  "Window Shutter Staining and Finishing",
  "Trim Painting with One Coat",
  "Trim Staining and Finishing",
  "Stucco Acrylic Latex Painting",
  "Stucco Elastomeric Painting",
  "Stucco Masonry Painting",
  "Stucco Lime Washing",
  "Brick Acrylic Latex Painting",
  "Brick Elastomeric Painting",
  "Brick Masonry Painting",
  "Brick Lime Washing",
  "Concrete Epoxy Painting",
  "Concrete Acrylic Latex Painting",
  "Concrete Masonry Painting",
  "Concrete Staining",
  "Adjustable Helical Post Foundation Installation",
  "Plastic Adjustable Pedestal and Framing Installation",
  "Concrete Blocks and Lumber Foundation Installation",
  "Pressure-Treated Wood Decking Installation",
  "Composite Decking Installation",
  "Deck Stairs Installation (Up to 4 Feet)",
  "Deck Stair Balusters Installation",
  "Deck Railing Installation",
  "Glass Railing Installation",
  "Glass Deck Gate Installation",
  "Aluminum Deck Gate Installation",
  "Non-Slip Aluminum Nosing Installation",
  "Deck Plank Removal",
  "Deck Sanding, Staining, and Finishing",
  "Premium Cedar Fence Installation",
  "Western Red Cedar Fence Installation",
  "Picket Fence Installation",
  "Vinyl Fence Installation",
  "Chain Link Fence Installation",
  "Metal Fence Installation",
  "Composite Fence Installation",
  "Composite Fence on Concrete Installation",
  "Driveway Metal Gate Installation",
  "Single Automatic Gate Opener Installation",
  "Cedar Pergola Kit Installation",
  "Concrete Column Pergola Installation",
  "Polycarbonate Roof Installation",
  "Pergola Removal",
  "Cedar Gazebo Kit Installation",
  "Concrete Column Gazebo Installation",
  "Gazebo Roof Installation",
  "Gazebo Removal",
  "Outdoor Furniture Assembly",
  "Outdoor Storage Concrete Slab Foundation Installation",
  "Outdoor Storage Square Patio Stone Basement Installation",
  "Outdoor Storage Shed Installation",
  "Carport Installation",
  "Storage Building Kit Installation",
  "Patio Cover Installation",
  "Outdoor Storage Removal",
  "Swing Sets Installation",
  "Playhouse Installation",
  "Sandbox Installation",
  "4-Step Outdoor Stair Installation",
  "5-Step Outdoor Stair Installation",
  "6-Step Outdoor Stair Installation",
  "8-Step Outdoor Stair Installation",
  "6-Foot Staircase Landing Installation",
  "8-Foot Staircase Landing Installation",
  "Outdoor Staircase Concrete Foundation Pillar and Columns Installation",
  "Outdoor Staircase Adjustable Ground Spike Foundation Installation",
  "Outdoor Staircase Step Replacement",
  "Outdoor Staircase Hand Rail Replacement",
  "Outdoor Staircase Removal (Per Rise)",
  "Wooden Walkway Installation",
  "Wooden Walkway Sanding and Staining",
  "Wooden Walkway Removal",
  "Boat Dock Installation",
  "Cedar Dock Decking Installation for Boat Dock Systems",
  "Gangway Installation",
  "10 ft. x 10 ft. Medium Freeboard Floating Dock Installation",
  "4 ft. x 10 ft. Commercial Grade Floating Dock Installation",
  "8 ft. x 10 ft. Aluminum Floating Swim Raft with Resin Top and Resin Dock Installation",
  "4 ft. x 10 ft. Aluminum Floating Dock with Resin Top Installation",
  "Outdoor Carpentry\t Inspection and Assessment",
  "Outdoor Carpentry\t Pest Prevention",
  "Outdoor Carpentry\t Refinishing",
  "Outdoor Carpentry Winter Prep",
  "Outdoor Carpentry\t Summer Prep",
  "Outdoor Electrical Panel Installation",
  "Circuit Breaker Replacement",
  "Outdoor Electrical Panel Cleaning and Lubricating",
  "Outdoor Electrical Panel Emergency Repairs",
  "Outdoor Electrical Panel Safety Inspection",
  "Backyard Outlet Installation",
  "Weatherproof Outlet Installation",
  "Backyard Outlet with Switch Installation",
  "Power Pedestal for RV Installation",
  "Running Power Cable for Installing a Power Pedestal",
  "EV Charger Installation",
  "Running Power Cable for Installing an EV Charger",
  "Pool Heater Installation",
  "Pool Pump Motor Replacement",
  "Sauna Heater Installation",
  "Hot Tub Pump Installation",
  "Wet Rated Outdoor Ceiling Fan Installation",
  "Mounting Bracket and Canopy Replacement",
  "Attach and Rebalance Blades",
  "Outdoor Home Theater Installation",
  "Rock Speakers Installation",
  "Whole House Propane/Natural Gas Generator Installation",
  "Whole House Generator Maintenance",
  "Battery Terminal Installation",
  "Wind Turbine Installation",
  "Wind Turbine Foundation Installation ",
  "Comprehensive System Evaluation",
  "Electrical Panel and Circuit Breakers Inspection",
  "Outdoor Electrical Seasonal Preparation",
  "Off Grid Solar 2 kW System Installation",
  "Monocrystalline Solar Panels Installation",
  "Outdoor Electrical Regular Inspections",
  "Outdoor Electrical Troubleshooting and Emergency Repairs",
  "Outdoor Electrical Wiring Maintenance",
  "Deck and Patio Pressure Washing",
  "Deck and Patio Soft Washing",
  "Deck and Patio Deep Cleaning Solutions",
  "Driveway Pressure Washing",
  "Driveway Soft Washing",
  "Driveway Deep Cleaning Solutions",
  "Hot Tub Regular Cleaning",
  "Hot Tub Water Treatment and Cleaning",
  "Vinyl Siding Cleaning",
  "Wood Siding Cleaning",
  "Brick and Stone Cleaning",
  "Fence Pressure Washing",
  "Fence Soft Washing",
  "Fence Stain and Spot Removal",
  "Gutter Debris Removal and Pressure Washing",
  "Gutter Cleaning Using Scaffold",
  "Roof Soft Washing",
  "Roof, Gutter and Solar Panel Cleaning Combo",
  "Outdoor Furniture Manual Cleaning",
  "Exterior Lighting Fixture Cleaning",
  "Exterior Decorative Element Cleaning",
  "Regular Outdoor Pool Cleaning",
  "Pool Shock Treatment",
  "Pool Filter and Equipment Maintenance",
  "Outdoor Glass Cleaning",
  "Outdoor Floor-to-Ceiling Glass Cleaning on a Single Storey Building",
  "Outdoor Floor-to-Ceiling Glass Cleaning on a 2-4 Storey Building",
  "Outdoor High-Rise Window Cleaning",
  "Garage Door Cleaning",
  "Landscape Path Light Kit (6-10 lights) Installation",
  "Solar LED In-Ground Path Light Installation",
  "Deck Post Lighting Installation",
  "Hardwired Path Light Installation",
  "String Light Kit Installation",
  "Deck/Step Light Installation",
  "Deck Post Light Installation",
  "Single-Story Wall Light Installation",
  "2-3 Story Wall Light Installation",
  "Wall Pack Lights Installation",
  "Area Lights Installation",
  "Underwater Light Installation",
  "Smart Outdoor Lighting System Installation (7 lights)",
  "Smart Outdoor Lighting System Installation (15 lights)",
  "Roofline and Eaves Installation on a One-Story Building",
  "Roofline and Eaves Installation on a 2-3 Story Building",
  "Medium Tree and Shrub Wrapping",
  "Large Tree and Shrub Wrapping",
  "Christmas Lighting Installation from Customer Materials (Labor Only)",
  "Christmas Lights Removal",
  "Outdoor Fixture Cleaning",
  "Outdoor Bulb Replacement",
  "Outdoor Electrical System Maintenance",
  "Tile Roofing Repair ",
  "Flashing Repair",
  "Temporary Leak Repairs",
  "Roof Sheathing Patch/Plug Repair (up to 8 inch x 8 inch)",
  "Shingle Roof Removal",
  "Laminate Shingle Roof Installation",
  "Cedar Shingles Roof Installation",
  "Metal Roof Installation",
  "Metal Roof Painting",
  "Metal Roof Removal",
  "Tile Roof Repair",
  "Elastomeric roof coating",
  "Self-Adhering Modified Bitumen Roof Installation",
  "Bitumen Roof Removal",
  "Silicone Reflective Roof Coating Installation",
  "Roof Leak Detection and Assessment",
  "Comprehensive Roof Inspection",
  "Roof Damage Inspection",
  "Gutter and Drainage Evaluation",
  "Gutter Downspout Installation",
  "Drip Edge and Gutter Installation for Single-Story Houses",
  "Drip Edge and Gutter Installation for 2-3 Story Houses",
  "Gutter Repair",
  "Gutter Removal",
  "Ridge Vent Installation",
  "Gravity Roof Ventilator Installation",
  "Static Ventilator Installation",
  "Solar Powered Attic Fan Installation",
  "Roof Turbines Installation",
  "Roof Ventilation Maintenance",
  "Tubular Skylights Installation",
  "Fixed Skylight Installation",
  "Venting Skylight Installation",
  "Curb-Mount Skylight Installation",
  "Skylight Removal",
  "OSB Sheathing Install",
  "Plywood Sheathing Installation",
  "Steep Roof Plywood Sheathing Installation",
  "Steep Roof OSB Sheathing Installation",
  "OSB Sheathing Removal",
  "Plywood Sheathing Removal",
  "Regular Lawn Mowing",
  "Lawn Edging and Trimming",
  "Lawn Aeration and Scarifying",
  "Spring Lawn Revitalization",
  "Autumn Lawn Preparation",
  "Lawn Winterization",
  "Faded Grass Painting",
  "Lawn Hand Seeding",
  "Lawn Hydroseeding",
  "Lawn Sod Installation",
  "Artificial Grass Installation",
  "Lawn Edging Installation ",
  "Tree Removal (Under 12” Diameter, Large Canopy)",
  "Tree Removal (12” to 24” Diameter, Large Canopy)",
  "Tree Removal (24” to 36” Diameter, Large Canopy)",
  "Tree Stump Grinding",
  "Tree Formative Pruning",
  "Small Tree Planting (Up to 2’ Tall)",
  "Medium Tree Planting (3’ to 5’ Tall)",
  "Large Tree Planting (Over 6’ Tall)",
  "Medium Size Tree Relocation",
  "Shrubs Planting",
  "Perennial Grasses Planting",
  "Organic Mulching (Up to 3” Deep)",
  "Organic Mulching for Playgrounds",
  "Pea Gravel Pebble Mulching",
  "Mulch Replacement and Top-Up",
  "Mulch Color Covering",
  "Ground Cover Rocks Installation",
  "Erosion Control Rocks Installation",
  "Rock Wall Installation",
  "Install Plastic Landscape Edging",
  "Install Metal Landscape Edging",
  "Install Natural Stone Landscape Edging",
  "Install Brick Landscape Edging",
  "Install Wood Landscape Edging",
  "Install Paver Landscape Edging",
  "Raised Garden Bed Installation (Wood)",
  "Raised Garden Bed Installation (Corten Steel)",
  "Raised Garden Bed Installation (Galvanized Steel)",
  "Hedge Planting",
  "Hedge Pruning",
  "Natural Path Installation",
  "Concrete Walkway and Path Installation",
  "Pavers Walkway and Path Installation",
  "Brick Walkway and Path Installation",
  "Stepping Stone Walkway and Path Installation",
  "Crushed Stone or Gravel Path Installation",
  "Surface Maintenance and Weed Control",
  "Small Landscape Fountain Installation",
  "Preformed Pond Installation",
  "Ponds and Fountains Maintenance",
  "Sprinkler Systems Installation",
  "Irrigation Timers and Controllers Installation",
  "Drip Irrigation System Installation",
  "Raised Bed Garden Drip Irrigation System Installation",
  "Irrigation System Winterization",
  "Irrigation System Maintenance",
  "French Drain System Installation",
  "Downspout Runoff Installation",
  "Landscape Drainage Solutions Installation",
  "Driveway Drainage Solutions Installation",
  "Yard Drainage Solutions Installation",
  "Drainage System Cleaning",
  "Aluminum Frame Greenhouse Installation",
  "Metal Orangerie Installation",
  "Greenhouse Seasonal Cleaning",
  "Outdoor Grill Assembly",
  "Outdoor Grill Cleaning",
  "Outdoor Kitchen Cabinets Installation",
  "Outdoor Kitchen Built-In Grill Installation",
  "Outdoor Kitchen Built-In Grill Installation",
  "Outdoor Kitchen Sink Installation",
  "Outdoor Kitchen Cleaning",
  "Outdoor Kitchen Removal",
  "Fire Pit Kit Installation",
  "Seat Wall Installation",
  "Fire Pit Cleaning",
  "Fire Pit Removal",
  "Compact Outdoor Fireplace Installation",
  "Compact Wood Box Installation",
  "Compact Outdoor Hearth Installation",
  "Fireplace Cleaning",
  "Fireplace Removal",
  "Infrared Ceiling-Mounted Electric Heater Installation",
  "Infrared Electric Heater Replacement",
  "Hot Tub Installation",
  "Hot Tub Maintenance",
  "Swimming Pool Site Preparation",
  "Hard-Sided Swimming Pool Installation",
  "Frame Swimming Pool Installation",
  "Cartridge Pool Filter Replacement",
  "Outdoor Pool Pump Replacement",
  "Outdoor Pool Winterization",
  "Outdoor Pool Opening",
  "Built-In Outdoor Cooler Installation",
  "Outdoor Refrigeration Electrical Repair",
  "Outdoor Refrigeration System Maintenance",
  "Outdoor Mist Cooling System for Small to Midsize Patio Installation",
  "Outdoor Mist Cooling System for Mid to Large Patio Installation",
  "Wooden Clapboard Siding Installation on a Single-Story Building",
  "Wooden Clapboard Siding Installation on a 2-3 Story Building",
  "Cedar Wood Shingle Siding Installation on a Single-Story Building",
  "Cedar Wood Shingle Siding Installation on a 2-3 Story Building",
  "Plywood Siding Panel Installation on a Single-Story Building",
  "Plywood Siding Panel Installation on a 2-3 Story Building",
  "Grid Siding Board Installation on a Single-Story Building",
  "Grid Siding Board Installation on a 2-3 Story Building",
  "Wood Siding Removal",
  "Vinyl Siding Installation on a Single-Story Building",
  "Vinyl Siding Installation on a 2-3 Story Building",
  "Vinyl Siding Repair",
  "Vinyl Siding Removal",
  "Thin Brick Veneer Removal",
  "Thin Brick Veneer Installation on a Single-Story Building",
  "Thin Brick Veneer Installation on a 2-3 Story Building",
  "Brick Veneer Sealing",
  "Brick Veneer Pointing and Repointing",
  "Brick Veneer Damage Repair",
  "Old Cladding Removal",
  "Stone Cladding Surface Preparation",
  "Natural Stone Installation on a Single-Story Building",
  "Natural Stone Installation on a 2-3 Story Building",
  "Manufactured Stone Veneer Installation on a Single-Story Building",
  "Manufactured Stone Veneer Installation on a 2-3 Story Building",
  "Faux Stone Siding Installation on a Single-Story Building",
  "Faux Stone Siding Installation on a 2-3 Story Building",
  "Stone Cladding Column Wrap",
  "Stone Cladding Protective Sealants Application",
  "Traditional Stucco Application on a Single-Story Building",
  "Traditional Stucco Application on a 2-3 Story Building",
  "Old Stucco Removal on a Single-Story Building",
  "Old Stucco Removal on a 2-3 Story Building",
  "Galvanized Steel Panel Installation",
  "Old Cladding Removal",
  "Glass Blocks Installation",
  "Glass Blocks Removal",
  "Composite Siding Installation on a Single-Story Building",
  "Composite Siding Installation on a 2-3 Story Building",
  "Fiber Cement Siding Installation on a Single Story Building",
  "Fiber Cement Siding Installation on a 2-3 Story Building",
  "Composite Paneling Removal on a Single-Story Building",
  "Composite Paneling Removal on a 2-3 Story Building",
  "Fiber Cement Trim Board Installation on a Single-Story Building",
  "Fiber Cement Trim Board Installation on a 2-3 Story Building",
  "Trim Engineered Treated Wood Siding Installation on a Single-Story Building",
  "Trim Engineered Treated Wood Siding Installation on a 2-3 Story Building",
  "PVC Trim Installation on a Single-Story Building",
  "PVC Trim Installation on a 2-3 Story Building",
  "Custom bent aluminum Installation",
  "Texture Soffit Installation",
  "Trim and Molding Removal",
  "House Wrap Installation",
  "House Wrap Removal",
  "Perimeter Bug Barrier Installation",
  "Bird Spikes Installation",
  "Screening Installation",
  "Screening Replacement",
  "Routine Façade Inspections",
  "Façade Structural Assessment",
  "Graffiti Removal",
  "Concrete & Masonry Waterproofing",
  "Exterior Wood Façade Waterproofing",
  "Protection Façade Against Moisture",
  "4 WiFi Security Camera System with Monitor Installation",
  "8 WiFi Security Camera System with Monitor Installation",
  "16 Security Camera System with Human & Vehicle Detection Installation",
  "Battery-powered Wireless Smart Home Security Camera Installation",
  "Small Solar Panel for Outdoor Cameras Installation",
  "Gutter Mount Security Camera and Solar Panel Installation",
  "Maintenance (battery replacement, cleaning)",
  "Motion-Sensing Security Alarm Installation",
  "Door/Window Alarm Installation",
  "Wireless Security System, 14 Piece Installation",
  "Video Doorbell Installation",
  "Maintenance and Battery Pack Replacement",
  "Fingerprint WiFi Smart Lock Installation",
  "Over Existing Deadbolt Smart Lock Installation",
  "Smart Door Lock with Bluetooth and Pushbutton Keypad Installation",
];

/**
 * Main function: loops over allServices, calls the Embeddings API,
 * and saves the results in "services-with-embeddings.json" in the /data/ folder.
 */
async function main() {
  // We'll store results here before saving to JSON
  const outputData: Array<{
    id: string;
    title: string;
    embedding: number[];
  }> = [];

  // Loop over the entire list
  for (let i = 0; i < allServices.length; i++) {
    const serviceTitle = allServices[i];
    const serviceId = `svc-${i + 1}`;

    console.log(`[${i + 1}/${allServices.length}] Embedding: "${serviceTitle}"`);

    // Call OpenAI Embeddings
    const response = await openai.embeddings.create({
      model: "text-embedding-3-small", // or text-embedding-3-large
      input: serviceTitle,
      encoding_format: "float",        // returns a float[] array
      // optionally: dimensions: 512, if you want to reduce vector size
    });

    const vector = response.data[0].embedding as number[];

    // Push into our output array
    outputData.push({
      id: serviceId,
      title: serviceTitle,
      embedding: vector,
    });

    // Optional small delay to avoid hitting rate limits
    await new Promise((r) => setTimeout(r, 150));
  }

  // Write to JSON
  const outPath = path.join(process.cwd(), "data", "services-with-embeddings.json");
  fs.writeFileSync(outPath, JSON.stringify(outputData, null, 2), "utf8");

  console.log(`\nDone! Saved ${outputData.length} services to: ${outPath}`);
}

// Execute
main().catch((err) => {
  console.error("Error in generate-embeddings script:", err);
  process.exit(1);
});